### ISSUE TITLE
SAML 2 Implementation

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#2941]
Enable SAML 2.0 integration for idp as well as sp.

## Tasks

- [x] #3088  
- [ ] ~~#3089~~
- [ ] ~~#3090~~
- [x] #3091
- [x] #3092
- [x] #3094
- [x] #3336
- [x] #3440
- [x] #3612

## SAML2.0 SPs we know customers are interested in

- [ ] Cohesity DataPlatform
- [ ] Rubrik CDM
- [ ] VMWare vCloud Director
- [ ] Citrix Netscaler in combination with Citrix Storefront
- [ ] AzureAD SSO (needs actions and additional configuration for the limited algorithms with SHA1)
- [ ] Google Workspace SSO
- [x] AWS SSO
- [x] Auth0 
- [x] Ping-Identity
- [x] OneLogin
- [ ] Fastly 
- [x] Gitlab SaaS
- [x] Atlassian Cloud
- [x] hin.ch

@stebenz feel free to extend this list with your SPs

**Comment by mffap** [comment]
We should test with Gitlab SaaS and Atlassian, please

**Comment by mffap** [comment]
Another one to test would be hin.ch with SAML2.0. Adding to the top list.

**Comment by fforootd** [comment]
> Another one to test would be hin.ch with SAML2.0. Adding to the top list.

Yes, but i don't think we get easy access there

**Comment by mffap** [comment]
> > Another one to test would be hin.ch with SAML2.0. Adding to the top list.
> 
> Yes, but i don't think we get easy access there

Agreed. Checked it out and seems to cumbersome atm. Tested Atlassian and Gitlab and seems to work fine.

**Comment by fforootd** [comment]
I think we can close this OKR goals since we reached it.

We can keep  the two issues open for further tracking

- #3089
- #3090
