### ISSUE TITLE
[Epic]: External login templates

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#2998]
As a ZITADEL Admin/Developer I want to be able to enable/disable the most common identity brokers and just adding the needed configuration, so I do not have to find the whole configurations of the specific providers.

**Acceptance Criteria**
- [x] I can enable/disable the identity providers on the instance and organisation level
- [x] I only have to setup my specific informations (client id, client secret)
- [ ] I can upload a picture for my identity provider
- [x] The required providers are available
- [x] I am able to set the following settings on my identity provider
      - Enable/Disable just in time provisioning
      - Allow Linking with an existing user
      - Just in time update (Updated information on the provider will be written to the user in ZITADEL)
      - Enable/Disable auto register
      - Which fields should be mapped from the provider to ZITADEL

**Required providers**
- [x] Generic OIDC
- [x] Generic OAuth 2.0
- [x] Generic JWT IdP
- [x] Github
- [x] Gitlab
- [x] Google
- [x] Microsoft AzureAD Tenants
       - Possibility to set emails to verified
       - AzureAD does not send amr and acr

**Additional Providers**
- [ ] #2761 
- [ ] Google Workspace
- [ ] Microsoft Common
- [ ] [Microsoft Live](https://github.com/zitadel/zitadel/issues/5130)
- [ ] [Auth0](https://github.com/zitadel/zitadel/issues/5125)
- [ ] [OKTA](https://github.com/zitadel/zitadel/issues/5129)
- [ ] [Keycloak](https://github.com/zitadel/zitadel/issues/5126) (realm based OIDC)
- [ ] [ZITADEL](https://github.com/zitadel/zitadel/issues/5127)
- [ ] [Discord](https://github.com/zitadel/zitadel/issues/5128)
- [ ] [LinkedIn](https://github.com/zitadel/zitadel/issues/5123)

**Additional Information**
Implement idp template possibility, get some inspiration from https://github.com/markbates/goth

- [x] #4431
- [x] #4432
- [x] #4433
- [x] #4434
- [ ] #4435

**Comment by fgerschwiler** [comment]
Possible providers
- Apple ID
- Microsoft Common
- Microsoft Live
- Microsoft Tenants (AzureAD)
- Github.com
- Gitlab.com (OIDC)
- Google
- Google Workspace
- Generic OIDC
- Generic OAuth 2.0
- Generic JWT IdP
- Generic SAML 2.0 SP
- Auth0
- OKTA
- Keycloak (realm based OIDC)
- ADFS (SAML or OIDC)
- ZITADEL

**Comment by Herdo** [comment]
@hifabienne @mffap Will this cover [this new suggestion](https://github.com/zitadel/zitadel/discussions/4125)?

**Comment by livio-a** [comment]
@Herdo we're going to cover them with `Generic OAuth 2.0` template where you will have to specify the endpoints and mapping like in your suggestion.
I'll create a link to this issue there as well.

**Comment by fforootd** [comment]
@hifabienne I think we could take some inspiration of this project https://github.com/markbates/goth.

**Comment by mffap** [comment]
@hifabienne I found that the templates for required providers will be shipped with https://github.com/zitadel/zitadel/issues/4431. Is there also an issue for the "additional providers" mentioned in this epic?

**Comment by hifabienne** [comment]
> @hifabienne I found that the templates for required providers will be shipped with #4431. Is there also an issue for the "additional providers" mentioned in this epic?

No not yet. We first want to implement the required ones and then see what is needed by our customers and community. The epic only focuses on the required ones. Also this gives them the possibility to make a pr for additional providers if needed

**Comment by mffap** [comment]
> > @hifabienne I found that the templates for required providers will be shipped with #4431. Is there also an issue for the "additional providers" mentioned in this epic?
> 
> No not yet. We first want to implement the required ones and then see what is needed by our customers and community. The epic only focuses on the required ones. Also this gives them the possibility to make a pr for additional providers if needed

Having an issue or discussion for it would make it easier to upvote specific providers (if you can't implement yourself).

**Comment by hifabienne** [comment]
> > > @hifabienne I found that the templates for required providers will be shipped with #4431. Is there also an issue for the "additional providers" mentioned in this epic?
> > 
> > 
> > No not yet. We first want to implement the required ones and then see what is needed by our customers and community. The epic only focuses on the required ones. Also this gives them the possibility to make a pr for additional providers if needed
> 
> Having an issue or discussion for it would make it easier to upvote specific providers (if you can't implement yourself).

You are right. I will create some issues for them and reference to this issue as we will not start implementing till this is finished

**Comment by hifabienne** [comment]
@livio-a which of the additional are already possible with your implementation.
I think the following will already work Google workspace, and not sure about Microsof

**Comment by loickal** [comment]
Hey there,

I would love to have AppleID also available

Best regards

**Comment by s0l4r** [comment]
I'm not sure this is the correct place to put this, but since Apple was mentioned here I will this site to the list. Maybe not are are relevant to implement, but this site has an impressive list of available sites with login providers: https://socialiteproviders.com/about/ (in the left menu)
