### ISSUE TITLE
Serverless Infrastructure Provisioning

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#3335]
As an infrastructure operator, I want to be able to automatically provision reproducible infrastructure

- [x] caos/zitadel-cloud#2
- [x] caos/zitadel-cloud#3
- [x] caos/zitadel-cloud#4
- [x] caos/zitadel-cloud#5
- [x] caos/zitadel-cloud#6
- [x] caos/zitadel-cloud#7
- [x] caos/zitadel-cloud#9
- [x] zitadel/zitadel#3496
- [x] zitadel/zitadel#3587
- [ ] zitadel/zitadel#3588
- [x] zitadel/zitadel#3589
- [x] zitadel/zitadel#3590
- [x] zitadel/zitadel#4160
- [x] zitadel/zitadel#3592
- [x] zitadel/zitadel#3593
- [x] caos/zitadel-cloud#17
- [x] caos/zitadel-cloud#18

**Comment by hifabienne** [comment]
@eliobischof should we close this issue? Only one is left and for this, we have a separate issue?

**Comment by eliobischof** [comment]
Let's close it
