### ISSUE TITLE
🥳 Version 2 Release preparations 🍿 

### ISSUE THREAD

**Issue by fforootd** [zitadel/zitadel#4064]
## Description

This issue is to prepare the release of version 2 of ZITADEL 🥳 

## Migration for v2-alpha users

If you were running a ZITADEL v2-alpha release you need to update two things:

- [x] If you used a custom `S3DefaultInstance` you need to update this to `FirstInstance` #4003 
- [x] To allow support for postgresql we are creating a dedicated config for cockroachDB #3998

Old database config:
```yaml
Database:
  Host: localhost
  Port: 26257
  Database: zitadel
  MaxOpenConns: 20
  MaxConnLifetime: 30m
  MaxConnIdleTime: 30m
  Options: ""
  User:
    Username: zitadel
    Password: ""
    SSL:
      Mode: disable
      RootCert: ""
      Cert: ""
      Key: ""

AdminUser:
  Username: root
  Password: ""
  SSL:
    Mode: disable
    RootCert: ""
    Cert: ""
    Key: ""
...
``` 
New database config:
```yaml
Database:
  cockroach:
    Host: localhost
    Port: 26257
    Database: zitadel
    MaxOpenConns: 20
    MaxConnLifetime: 30m
    MaxConnIdleTime: 30m
    Options: ""
    User:
      Username: zitadel
      Password: ""
      SSL:
        Mode: disable
        RootCert: ""
        Cert: ""
        Key: ""
    Admin:
      Username: root
      Password: ""
      SSL:
        Mode: disable
        RootCert: ""
        Cert: ""
        Key: ""
...
``` 

## Things Todo

- [x] rename branch main to v1
- [x] Switch default branch to the new main in GitHub (currently v2-alpha) @fforootd @livio-a 
- [x] Add latest image tags and update releaserc.js #4060 @fforootd @thesephirot 
- [x] Update docs to use the v2 tag or latest #4046 
- [x] Update Links to GitHub Paths in #4046 @fforootd 
- [x] Merge #4046 to update docs @fforootd 
- [x] Update Links to docs @fforootd https://github.com/caos/zitadel-next/pull/271
- [x] Remove v2/v1 switch @hifabienne @peintnermax https://github.com/caos/zitadel-next/pull/262
- [x] Default to new pricing @hifabienne @peintnermax https://github.com/caos/zitadel-next/pull/262
- [x] Trigger Algolia Crawler @fforootd 
- [x] Update Netlify Branch

## Announcement Channels

- [ ] HN
- [ ] Reddit
- [ ] Twitter
- [ ] Linkedin
- [ ] Discord
- [ ] Contact GitHub for their release channels

**Comment by fforootd** [comment]
We got a release right here https://github.com/zitadel/zitadel/releases/tag/v2.0.0
