### ISSUE TITLE
Extending ZITADEL Actions

### ISSUE THREAD

**Issue by fforootd** [zitadel/zitadel#4265]
# Phase 1

## Allow Actions to communicate with a http endpoint

- [x] #4309
- [x] #4311
- [x] #4313
- [x] #4320

## Allow Actions to add custom claims (id_tokens, access_tokens, userinfo, introspect)

- [x] Implement that custom claims can be asserted => see `AppendClaim` in https://github.com/zitadel/zitadel/issues/4321
- [x] Define and document what claims are protected (some claims should not be able to be overloaded, like the `sub`, ...) => as it's only allowed to add additional claims all claims set by zitadel are protected

## Extend Flows and Triggers

- [x] https://github.com/zitadel/zitadel/issues/4321 

## Extend API's

- [x] #4351

# Phase 2

## Customer request to add org metadata to the claims (even across organizations)

- Allow Actions to use a Service User to get brother permissions and access other organizations metadata
- Provide management api as client to read things like [org-metadata](https://github.com/zitadel/zitadel/issues/4167)
- **Question**: where should we allow this? Only on external or internal users

## Extend Flows and Triggers

- TBD

# Phase 3

## General DevUX Improvements

- Create a debug and preview option
- Create a way of injecting variables (logable) and secrets (not logable)
- Create retry settings for backpressure handling
- Store executions logs for analysis as events
- Allow A/B testing while deploying / activating actions
- Allow upload from source control

## Ideas & Inputs

- [Username Rules](#3956)
- [Deny eMail Domains in registration](https://discord.com/channels/927474939156643850/1039648934676676700)
- ...

**Comment by fforootd** [comment]
Could relate to https://github.com/caos/caos-sales/issues/216 and https://github.com/caos/caos-sales/issues/209

**Comment by adlerhurst** [comment]
not clarified yet: https://github.com/zitadel/zitadel/issues/4312

**Comment by adlerhurst** [comment]
additional flow types:

- [ ] create action during set user info to add custom claims (only extend)

**Comment by adlerhurst** [comment]
added api in phase 1

**Comment by adlerhurst** [comment]
assumption: if loading actions fails it's okay to proceed the process

**Comment by fforootd** [comment]
Some thoughts concept wise on the flows and triggers.

I think we should seperate the flow along the following topics:

## Registration

- Check or write something to an external system (CRM, ERP,...)
- Deny registration for certain IP ranges or Geo regions (display error or redirect to external page)
- Dynamicly change registration fields (write data to metadata or external system)
- Enforce username semantics
- Discover organization to register the user

### Triggers

- register-start
- register-end

## Verification

- Check or write something to an external system (CRM, ERP,...)
- Deny registration for certain IP ranges or Geo regions (display error or redirect to external page)

### Triggers

- verification-start
- verification-end 

## Authentication

- Check or write something to an external system (SOC System, CRM, ...)
- Deny login for certain IP ranges or Geo regions
- Customize login behaviour

### Triggers

- login-start
- login-end

## Credential Changes

- Send mail to user when or external system (audit log) when somehting changes

### Triggers

- add/remove/change password/mfa/2f/passwordless 

## API Calls

- Modify API responses
- Deny API calles from certain IP or Geo regions

### Triggers

- token request
- introspect request
- userinfo request
- ...

**Comment by adlerhurst** [comment]
@fforootd is `end` defined as the last code executed before return to the client or write data?

**Comment by adlerhurst** [comment]
@livio-a @fforootd 

Here are the outcomes i've written down:

# Flows and Triggers

## Login/Reigster Flow

* pre-discovery-trigger: when you land on `/ui/login/login` # additional question here: or when you get on `/ui/login/authorize`?
* post-discovery-trigger: user was assigned to organisation

* pre-login-trigger: user exists, has been loaded. Executes trigger and after trigger something happens in the ui (e.g. redirect to password page)
  * FUTURE: possibility to manipulate next step (federation, authentication)
* post-login-trigger: after interactive user part, user session is valid, before protocol (oidc/saml) specific part continues. in oidc response code 302 will be sent to the client
* protocol-response-trigger: # is this still relevant?
  * oidc: /token, /userinfo, /introspect
  * saml: ?

* pre-register-trigger: before user events are written into eventstore. Mechanism to register user, which data will be written into eventstore.
  * add information metadata like idp into the `context`-param
* post-register-trigger: after events have been written to eventstore. (additional transactions possible)

**Comment by adlerhurst** [comment]
# Proposal

## On event

request.oauth.token (id, access and refresh token)
request.oauth.introspect
request.oidc.userinfo

```yaml
on: request.oauth.token
```

```yaml
on: [user.created, user.registered]
```

```yaml
on: 
    user:
        - created
        - registered
```

```yaml
on: 
    user:
        machine:
            - created
        human:
            - created

name: hodor
run: function hodor() {log.println("hodor")}
secret: secret.my.secret
```

```yaml
on: user.created
```

```yaml
before: event.user.created
```

```yaml
on: request.*
```

```yaml
on: [request.oauth.*, request.saml.*]
```

```yaml
on: 
    flow:
        login:
            - post
modules:
    - http
    - management
    - 
run: function addClaim(ctx, api) {api.addClaim("hodor", "hodor")}
```

```yaml
on: 
    flow:
        login:
            - post
modules:
    - http
    - management
    - 
run: https://github.com/zitadel/zitadel:v2.6.0
```

request
event
command

```yaml
on: 
    login:
        - post
    flow:
        login:
            - post
    user:
        - created

modules:
    - http
    - management
        readonly: true

steps:
    fetch: # storage, code, source
        secret: $GIT_TOKEN
        git: https://github.com/zitadel/zitadel:v2.6.0
    run-:
        run: ./zitadel/addClaim.js
        vars:
            - "key"
            - "value"
```

```yaml
on: 
    login:
        - post

modules:
    - http
    - management
        readonly: true

vars:
    asdf: "key"
    jkloe: "value"

functions:
    load-from-marketplace:
        uses: action/name@v2.6.0
        allowToFail: true
    exec-from-git:
        secret: $GIT_TOKEN
        git: https://github.com/zitadel/zitadel:v2.6.0
        # git: ssh://github.com/zitadel/zitadel:v2.6.0
        timeout: 20s
        run: ./zitadel/addClaim.js
        vars:
            asdf: "key"
            jkloe: "value"

templates: #gui
    login:
        success:
            git: https://github.com/zitadel/zitadel:v2.6.0
            # uses: action/name@v2.6.0
            template: ./my/login_success # folder contains html, css, js, i18n-files
```

**Comment by adlerhurst** [comment]
# current flows

## external authentication

### Post Authentication

- /login/externalidp/callback: if oidc
- /login/jwt/authorize

### Pre Creation

- /externaluser/option (register)
- /login/externalidp/callback: if oidc
- /login/jwt/authorize

### Post Creation

- /externaluser/option (register)
- /login/externalidp/callback: if oidc
- /login/jwt/authorize

## complement token

### Userinfo creation

- /oauth/v2/introspect
- AuthResponseToken
- CodeExchange
- RefreshTokenExchange
- Userinfo

### Pre access token creation

- /token (with bearer token)

**Comment by fforootd** [comment]
I think taking inspiration from github action is a great idea.

I think it boils down to the following structure:

## On

The on clause to define what invokes the action.
This can be multiple triggers like a [GH action](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on)
The elements usable to invoke are either ZITADEL resources (users, projects, org...) or flows (login, register,...)

```yaml
on: 
  flows:
    login:
      - post
  events:
    user:
      - created
    projects
```

## Modules

Modules can enable or disable certain API within an action.
I think we could use this to give users better control over what should be exposed in the runtim

```yaml
modules:
  - http
  - management
    readonly: true
```

## Vars

Good old global vars. I think we need some kind of `secret` as well.

```yaml
vars:
  foo: "bar"
  alice: "bob"
```

## Functions

The functions artifact defines where an action originates from.
At the moment we think of using git as storage and fetch the code at the moment of deployment of the action. 
We need to cache the code definitely to have a short latency during runtime.

Later on we can create a "marketplace" with predefined actions that can easily be used with the "use" instruction.

```yaml
functions:
  from-marketplace:
    uses: action/name@v2.6.0
    allowToFail: true
  from-git:
    secret: $GIT_TOKEN
    git: https://github.com/zitadel/zitadel:v2.6.0
    # git: ssh://github.com/zitadel/zitadel:v2.6.0
    timeout: 20s
    run: ./zitadel/addClaim.js
    vars:
      foo: "bar"
      alice: "bob"
```

## Templates

Templates are intended to allow customization of the login/register gui components.

```yaml
templates:
  login:
    success:
      git: https://github.com/zitadel/zitadel:v2.6.0
      # uses: action/name@v2.6.0
      template: ./my/login_success # folder contains html, css, js, i18n-files
```

**Comment by adlerhurst** [comment]
# simplified approach

It relies on the idea of pipelines by gitlab. You basically have two pipelines: `event` and `request`, represented in two files. There are no triggers like in the previous github actions based proposal.

the `event`-pipeline: is executed in background by nature (reactive).
the `request`-pipeline: is executed during an API call synchronously, by default.

A pipeline contains a list of jobs. Each of the jobs is executed sequentially if the pipeline applies. The jobs are executed in order

In a first phase the description of a request-job looks like this:

```yaml
jobs:
  my-job:
    allowFailure: bool
    isAsync: bool
    script:
      name: string representing the init function-name
      script: string ecma-script compliant function which at least contains the function with name declared in `my-job.script.name`
```

The request is passed to the function using the `ctx`-parameter containing ctx.request.{data}

event-job looks like this:

```yaml
jobs:
  my-job:
    allowFailure: bool
    script:
      name: string representing the init function-name
      script: string ecma-script compliant function which at least contains the function with name declared in `my-job.script.name`
```

The event are passed to the function using the `ctx`-parameter containing ctx.event.{payload}

In a second phase additional fields will be added to the job object.

Short list of addional fields:

```yaml
jobs: 
    my-job:
        if: {{condition}} # if condition applies the job is will be executed
```

**Comment by adlerhurst** [comment]
# use cases

## requests

- As a user I want react on each request to check if conditions of the request apply to my use cases. E.g. I want to check if the client is in an ip subnet

### login api

- As a user I want to extend the claims of the access token to add information needed in my app
- As a user I want to extend the claims of the id token to add information needed in my app
- As a user I want to extend the claims of user info to add information needed in my app

### register api

- As a user I want 

### grpc apis

## events

- As a user I want to react on created events because I want to notify foreign systems on behalf of events
- As a user I want to add additional commands before the events are created. E.g. to add metadata to a user

**Comment by adlerhurst** [comment]
brainstorming where to trigger actions/pipelines:
https://jamboard.google.com/d/1kz646GB_MXmHjX4sq05dXW3IwO2b35Fv3_rIjTMp8Ys/edit?usp=sharing

**Comment by mffap** [comment]
@fforootd or @hifabienne can you split out the next phases in new issues, please?

**Comment by adlerhurst** [comment]
export default as discussed here: https://github.com/zitadel/zitadel/discussions/4783

**Comment by livio-a** [comment]
@adlerhurst I think we can close this and create a new issue when needed for Phase 3, right?
