### ISSUE TITLE
Org Remove Findings

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4780]
I tested the organization remove feature and have some findingts, that are not blocking for merge but should be addressed later.

**Acceptance criteria**
- [x] Add organization remove to the admin api #4917
- [x] When I have deleted an organization, it is still listed in the organization overview with a removed state, if I go to the organization everything under it is not shown (users, projects, etc) this feels kind of strange #4837
- [x] OrgQuery should be extended with a state filter, where i can put a list of states, so I am able to load all states but not the removed #4917
- [x] Org Of ZITADEL Project should not be deletable #4875

**Comment by hifabienne** [comment]
I remove the open tasks and have created a new user story: #4974

**Comment by hifabienne** [comment]
@livio-a I think we can close this now, since the other prs are merged?
