### ISSUE TITLE
[Epic] Login API and improvement of Register API

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#5015]
As a developer, I want to be able to build my own login and register ui, so that I can customise it however I need it.

We have decided on implementing this feature with an MVP approach. The goal is to have a register and login with username password as first and than add more and more functionality.

## Acceptance criteria
- [x] #5486

### 1. Step
- [x] https://github.com/zitadel/zitadel/issues/5432
- [x] https://github.com/zitadel/zitadel/issues/5433
- [x] https://github.com/zitadel/zitadel/issues/5434

### 2. Step
- [x] #5464
- [x] #5017 
- [x] #5465
- [x] #5018 

### 3. Step
- [x] #5466
- [x] #5467
- [x] #5468
- [x] #5016
- [x] #5019 

### 4. Step
- [x] #5469
- [x] #5470
- [x] #5471
- [x] #5473
- [x] #5474
- [x] https://github.com/zitadel/typescript/issues/12

## 5. Step
- [x] #5478
- [x] https://github.com/zitadel/typescript/issues/13
- [x] https://github.com/zitadel/zitadel/issues/5481

## 6. Step
- [x] https://github.com/zitadel/typescript/issues/16

## Tasks to finish
- [x] #5472
- [x] #5477

### Backend
- [ ] https://github.com/zitadel/zitadel/issues/6239
- [ ] https://github.com/zitadel/zitadel/issues/6053

### Frontend
- [x] https://github.com/zitadel/typescript/issues/14
- [ ] https://github.com/zitadel/typescript/issues/17
- [ ] https://github.com/zitadel/typescript/issues/15
- [ ] https://github.com/zitadel/typescript/issues/18
- [ ] #5482

**Comment by livio-a** [comment]
General idea:
- Login (client) gets all it needs (from specific endpoints, see below)
- Login defines and executes its flow
  - e.g. requires password and 2FA check / passkeys
  - Maybe backend checks for fulfilment as well (but without order) 
- Resource based endpoints
  - Users
  - Policies
  - IDPs
  - Sessions
    - Password checks result in new session or update an existing session (if provided, e.g. by id)
    - Login with IDP
  - Texts 
  - Auth Request?
    - OIDC / SAML defines requirements / context (login_hint, org)
  - ...
- Backend might provide an event stream of a session
- Implementation:
  - Groundwork / remove technical depts by starting with registration
  - extend login step by step 

1. (1-2 weeks) Define / Specify resources and their endpoints / methods
  1.1. How to get / specify context (admin/mgmt/auth vs header/path/…)
  1.2. Happy path design for the simplest login possibility 
2. (1 week) Registration API definition (priority: 1. Users, 2. Policies, 3. IDPs, 4. Sessions, 5. Texts)
3. (2 weeks) Aggregate and event design
4. (4-5 weeks) Implementation of new aggregates / events
5. (2-3 weeks) Implement base work and registration in default login client
6. (1 week) Login API definition
7. (1 week) Update aggregate / event design
8. (1 week) Add possibility to switch instances between existing and new login
9. (3-4 weeks) Implementation of new aggregates / events
10. (3-4 weeks) Update Default login client with new possibilities

sum: 24

**Comment by hifabienne** [comment]
**1. Step**
- Groundwork (2 weeks)
   - Define Basics
   - Setup API
   - Setup UI

**2. Step**
- Backend: Register User with Password
   - Define API (Messages/Endpoints)
   - Command Side
   - Query Side
- Backend: Policies 
   - Define API (Messages/Endpoints)
   - Login Policy, Password Policy
- Frontend: Basic Implementation of Frontend
   - Basic Design
   - Read basic policies (Branding, Texts, etc) 

**3. Step**
- Backend: Setting on Instance for new/old Login
   - Feature Enable/Disable Policy?
   - Command Side
   - Query Side
   - Console
- Backend: Register User with External IDP
   - Define API (Messages/Endpoints)
   - Command Side
   - Query Side
- Backend Login User with Username / Password
  - Define API (Messages/Endpoints)
  - Command Side
  - Query Side
- Frontend: Register User with Password including Policies
  - Read required policies
  - Username/Password registration
  - Minimum required user fields (Firstname, Lastname, Email)

**Comment by jmls** [comment]
yes ! this ! ;) Willing to help with any beta/RC testing you need.

**Comment by 0xdeafbeef** [comment]
Will it be possible to add custom header | footer to all pages?

**Comment by kbumsik** [comment]
Just for reference, in Keycloak world there is a tool that creates a compatible Keycloak theme using React. I have been using it and this is one of reason I stay in Keycloak. 

https://github.com/keycloakify/keycloakify

**Comment by hifabienne** [comment]
@kbumsik @fenos 
We are building a typescript repository, with a default login and some default components.
At the moment it is still a private repository, but we will change to public shortly.
So if you don't want to build your UI from scratch you can just use the components or for the login and change what you need for more customization.

**Comment by mffap** [comment]
Not sure where to ask: will the new UI have a way to manage themes/ templates? With that I could customize the login, but keep the core application up to date with zitadel/typescript (?).

**Comment by hifabienne** [comment]
This issue will be closed, the open tasks are created as follow ups.
