### ISSUE TITLE
[epic] Events table is not locked while writing on an aggregate

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#5031]
# eventstore epic

As a developer i want to get the best performance out of the storage layer of ZITADEL.

## Background information

The storage layer of ZITADEL is split into 3 parts.

- Query side: all the read traffic hits this part of the storage layer. It doesn't want to make any changes and depending on the use case the data must be more or less actual
- Command side: all the write traffic this this par of the storage layer. It wants to make manipulations, for that it might read data to update field of an object
- Eventstore: All the traffic hits this layer. the command side might hit it twice first for reading last for writing and the query side for updating stale data

The focus of this epic is to optimise response latency for each storage layer. This can be achieved by optimising all the layers.

## eventstore

The eventstore framework has currently several missasuptions from the past which have to be corrected. Further readings [here](https://docs.google.com/document/d/1mBq610lxduM0kD1H3PrG7ESBVSYtv_bAq0uYT5alIJw/edit?usp=sharing)

The following tasks are based on the document mentione the line before.

### Phase 1 prepare current query side

- [x] https://github.com/zitadel/zitadel/issues/5030: queries only consider data older than the timestamp they hit the api
- [x] https://github.com/zitadel/zitadel/issues/5302
- [x] https://github.com/zitadel/zitadel/issues/5353  
      after that point the linking columns (`previous_aggregate_sequence`, `previous_aggregate_type_sequence`) are not needed anymore

### Phase 2 heart bleeding

- [x] https://github.com/zitadel/zitadel/issues/5358
- [ ] https://github.com/zitadel/zitadel/issues/5359

### Phase 3 correct eventstore model

- [x] https://github.com/zitadel/zitadel/issues/5354
- [x] https://github.com/zitadel/zitadel/issues/5355
- [x] https://github.com/zitadel/zitadel/issues/5357
- [x] https://github.com/zitadel/zitadel/issues/5356

### Phase 4 optimise by id queries

This phase needs further investigation because we need to know if we need an additional caching layer

### Phase 5 optimise search queries

This phase needs further investigation because we need to know if we need an additional caching layer, and if we should react on created events

### Phase 6 rethink current aggregates

There might be aggregates we have to redesign. project/application for example

**Comment by adlerhurst** [comment]
Link to phase: https://docs.google.com/document/d/1mBq610lxduM0kD1H3PrG7ESBVSYtv_bAq0uYT5alIJw/edit#heading=h.6sp2pay2tybc

**Comment by hifabienne** [comment]
1 Day for looking at the risk, result should be to know which implementation works best

**Comment by adlerhurst** [comment]
Document: https://docs.google.com/document/d/1mBq610lxduM0kD1H3PrG7ESBVSYtv_bAq0uYT5alIJw/edit?usp=sharing

The decision is to implement an evetstore based on sequences per aggregate id.

**Comment by adlerhurst** [comment]
@hifabienne this is my proposal for the epic:

# eventstore epic

As a developer i want to get the best performance out of the storage layer of ZITADEL.

## Background information

The storage layer of ZITADEL is split into 3 parts.

- Query side: all the read traffic hits this part of the storage layer. It doesn't want to make any changes and depending on the use case the data must be more or less actual
- Command side: all the write traffic this this par of the storage layer. It wants to make manipulations, for that it might read data to update field of an object
- Eventstore: All the traffic hits this layer. the command side might hit it twice first for reading last for writing and the query side for updating stale data

The focus of this epic is to optimise response latency for each storage layer. This can be achieved by optimising all the layers.

## eventstore

The eventstore framework has currently several missasuptions from the past which have to be corrected. Further readings [here](https://docs.google.com/document/d/1mBq610lxduM0kD1H3PrG7ESBVSYtv_bAq0uYT5alIJw/edit?usp=sharing)

The following tasks are based on the document mentione the line before.

### Phase 1 prepare current query side

- [ ] queries only consider data older than the timestamp they hit the api (existing user story)
- [ ] events are returned sorted by creation date AND sequence
- [ ] spoolers query events by creation date instead of sequence  
      after that point the linking columns (`previous_aggregate_sequence`, `previous_aggregate_type_sequence`) are not needed anymore

### Phase 2 correct eventstore model

- [ ] remove the unnecessary columns from the events table and the eventstore implementation
- [ ] add new event field `event_version` which describes the field definition of an event
- [ ] change the query and command side to version the event version instead of an object/aggregate
- [ ] remove the `aggregate_version` field from the eventstore

### Phase 3 heart bleeding

- [ ] implement eventstore implementation according to https://github.com/zitadel/zitadel/tree/eventstore-bench/internal/eventstore/v5  
  - includes remove of instance sequence
  - create new indexes
  - drop old indexes
- [ ] drop sql sequences

### Phase 4 optimise by id queries

This phase needs further investigation because we need to know if we need an additional caching layer

### Phase 5 optimise search queries

This phase needs further investigation because we need to know if we need an additional caching layer, and if we should react on created events

### Phase 6 rethink current aggregates

There might be aggregates we have to redesign. project/application for example

**Comment by hifabienne** [comment]
Will close this epic for now, as the open tasks are only clean up tasks and can be done at any point
