### ISSUE TITLE
[Epic]: Logviewer and Feedback loop for events

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#5102]
As ZITADEL administrators/developers we want to enable our customers and their end users to see the event log of their instance or their user and be able to flag suspicious events. So we are able to train AI models in the future for AI threat defens.

**Acceptance criteria**
- [ ] I want to be able to see all events of an instance
- [ ] I want to be able to flag any events that look suspicious to me
- [ ] As an authenticated user I want to see all events that happened on my user (human understandable)
- [ ] As an authenticated user I want to be able to flag an event that look suspicious to me
- [ ] An external system is able to get all events
- [ ] An external system is able to flag suspicious events

**Comment by adlerhurst** [comment]
1. (2 week) Add flag to events and create API
2. (2 week) Flag emails
3. (2 week) Flag user events
4. (2 week) Flag events as admin

sum: 8 weeks

**Comment by muhlemmer** [comment]
Discuss:

1. Improve full-stack logging
2. zitadel/oidc#291

**Comment by adlerhurst** [comment]
additional information required: must it be possible to flag execution logs as well?

**Comment by adlerhurst** [comment]
final assumption:

1. (1 week) Add call/request id to event and extend interceptor
2. (1 week) Add call/request id to access/execution logs
3. (1 week) add call/request id to stdout logs
4. (1 week) add id to access and execution log
5. (2 week) Write an event to flag previous events (malicious events/logs, severity, confidence level, description, cause, expected order of events (user can rearrange order of events), expected values of events, )
6. (1 week) api to assess the flag or unflag them
7. (1 week) projection for flagged calls/events/logs
8. (2 week) read api for log viewer
9. (2 week) Flag emails
10. (3 week) Logviewer for users
11. (3 week) Logviewer for admins
12. (1-2 week) add metrics endpoint flagged events count
13. (2 week) e2e test flagging


sum: 22 weeks

**Comment by mffap** [comment]
Example for a relevant event from a discovery call: 
Detect account sharing (ie. login/session from multiple locations/devices/... at the same time)

**Comment by elinashoko** [comment]
Thanks for filing this issue. As part of an ongoing backlog cleanup, we're closing issues that have had no activity in over 12 months.

If this is still relevant, let us know in a comment (or reopen the issue) and we'll take another look.

This issue will close in 30 days if there's no further activity.
