### ISSUE TITLE
Authentication Examples (Proposed Epic)

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#5124]
As a Developer, I want to use a basic Auth example so that I can quickly try out ZITADEL in my favorite language.

**Background** 

Goal of this EPIC is to provide for each defined language

- basic authentication and authorization examples and
- a quickstart guide.

Also the [Examples Docs](https://zitadel.com/docs/examples/introduction#libraries) page should be re-worked.

The initial focus is not on providing SDKs for each language, only for examples where an SDK already exists. SDKs, also providing access to our APIs and Auth, should be integrated to the examples at a later point.

See Phase 2 / Future Work further below for what is out of scope, but should be done after this Epic is completed.

**Acceptance criteria**

- [x] #5188
- [x] #5189
- [x] #5190
- [x] #5191
- [x] [React auth example](https://github.com/zitadel/zitadel/issues/7043)
- [x] #5223
- [x] https://github.com/zitadel/zitadel/issues/7045
- [x] https://github.com/zitadel/zitadel/issues/7046
- [x] [PHP Web auth example](https://github.com/zitadel/zitadel/issues/7047)
- [ ] Python3 Flask Web auth example
- [x] ASP.NET Core MVC Web auth example
- [x] #5192
- [ ] NodeJS Express API auth example
- [ ] PHP API auth example
- [ ] ASP.NET Core WebAPI API auth example
- [x] Docs: Overview Examples
- [x] Docs: Overview SDKs/Libraries
- [x] Docs: Overview Integration Guides
- [x] Github: Replace client libraries in README

## Examples Scope

This scope of features should be available as minimum in each of the example applications.
Differentiation between frontend and backend apps.
Managing ZITADEL resources via API is not included in the scope, but is left for Phase 2.

Recommended OIDC libraries (or SDK whenever available) should be used in the examples to handle Authentication and Authorization according to OIDC.

### Frontend

- Authentication with ZITADEL
  - Flows are language and client type specific (Defined in SDKs)
- Session persistence
- Authorization  / Roles
  - User: show own authorizations
  - Admin: access private route
- Loading User Profile
  - userinfo_endpoint
- Session Management
  - Refresh Tokens (mobile, server-side)
  - Silent refresh/silent sign-in (spa)
- Logout
  - End_session
  - Terminate local session

### Backend

- Authorization
  - Service User with PAT Token
- RBAC
  - Public Endpoint
  - Private Endpoint / Route
  - Private Scoped Endpoint / Route (read:messages)
- Check token against introspection_endpoint
  - Use roles scope (Don’t use “assert roles on authentication”)

## Docs: Overview Examples

Overview page with all examples for ZITADEL.
Frontend and Backend/API contains authentication and authorization examples.
Manage ZITADEL resources contains examples to show how to access ZITADEL's APIs

#### Single Page App

- React
- [Angular](https://github.com/zitadel/zitadel-angular)
- Vue

#### Native/Mobile App

- Flutter

#### Regular Web App

- [NextJS](https://github.com/zitadel/zitadel-nextjs)
- Go Web
- Java Spring Boot Web
- PHP Web
- Python3 Flask Web
- ASP.NET Core MVC Web

### Backend/API

- Go API
- NodeJS Express API
- Java Spring Boot API
- PHP API
- Python3 Flask
- ASP.NET Core WebAPI

### Manage ZITADEL Resources

Note: In Phase 1 link. See Phase 2 for expected minimal scope.

- .NET (replace: https://zitadel.com/docs/examples/call-zitadel-api/dot-net)
- Go (replace: https://zitadel.com/docs/examples/call-zitadel-api/go)
- NodeJS

### Overview of all ZITADEL SDKs

In Frontend and Backend/API we only mention libraries that fulfill our quality and security standards.
Libraries from third parties are marked as community libraries.
Each SDK/Library has links to the source code, example, and quickstart.
Under More libraries we can mention other recommended projects or links to further Libraries etc.

| Language / Framework | Link Github | User Authentication | Manage resources | Notes |
|--- | --- | --- | --- | --- |
| .NET     | [zitadel-net](https://github.com/smartive/zitadel-net) | ✔️ | ✔️ | `community` |
| Elixir   | [zitadel_api](https://github.com/jshmrtn/zitadel_api) | ✔️ | ✔️ | `community` |
| Go       | [zitadel-go](https://github.com/zitadel/zitadel-go) | ❌ | ✔️ | `official` |
| JVM      | 🚧 [WIP](https://github.com/zitadel/zitadel/discussions/3650) | ❓ | ❓ | TBD |
| Python   | 🚧 [WIP](https://github.com/zitadel/zitadel/issues/3675) | ❓ | ❓ | TBD |
| NodeJS   | [@zitadel/node](https://www.npmjs.com/package/@zitadel/node) | ❌ | ✔️ | `community` |

**User Authentication (explain)**

- Frontend: Authenticate user
  - SPA/Native/Mobile: PKCE (mandatory)
  - Web: PKCE or Code
- Backend: Check user authorization
  - Authorization Grant / JWT Profile (API client)
  - Client Secret Basic (API client)

**Manage resources (explain)**

- Authenticate Service User
- Manage ZITADEL resources, with scope:
  - Authentication
  - Management
  - Administration
  - System

**More**

Provide some more information about honorable mentions of community SDKs, Middleware, or standard-libraries for Authentication and Authorization.

- SDKs, today marked with "Auth check" X (Don't meet the standards)
- Middleware:
  - Authentication Helper for NodeJS: [PassportJS](https://github.com/buehler/node-passport-zitadel)
  - [Next-Auth Provider](https://next-auth.js.org/providers/zitadel)
- Link: https://github.com/casbin/awesome-auth
- > Use any of the Open ID Connect certified RP implementations in your preferred language. As certified OpenID Provider, ZITADEL is compatible with any of the implementations.

## Docs: Integration Guides

Replaces: https://github.com/zitadel/zitadel/pull/4554

### Configure external IDP (to be replaced)

Note: After completing https://github.com/zitadel/zitadel/issues/2998 these examples can be replaced with IDP templates.

- https://zitadel.com/docs/guides/integrate/auth0-oidc
- https://zitadel.com/docs/guides/integrate/auth0-saml
- https://zitadel.com/docs/guides/integrate/azuread-oidc
- https://zitadel.com/docs/guides/integrate/pingidentity-saml

### Services

- https://zitadel.com/docs/guides/integrate/gitlab-self-hosted
- https://zitadel.com/docs/guides/integrate/atlassian-saml
- https://zitadel.com/docs/guides/integrate/gitlab-saml
- https://zitadel.com/docs/guides/integrate/aws-saml

### Infrastructure

- https://zitadel.com/docs/guides/integrate/authenticated-mongodb-charts
- https://zitadel.com/docs/self-hosting/deploy/loadbalancing-example
- https://zitadel.com/docs/examples/identity-proxy/oauth2-proxy

### More SDKs

- Java
- Python
- PHP

### Extend examples and interact with zitadel apis via sdks

User profile (own user = auth api)

- Change password
- Setup OTP
- Setup Passkeys

User objects (all users = management api)

- Search: Receive list of all users with roles for an organization
- Create: Create a new verified user in an organization

### Integration Patterns

Frontend-Own API

- Frontend + API in same project
- Frontend + API in separate projects

Backend-for-frontend

- pattern with dapr and c# https://github.com/caos/caos-internal/issues/537
- cloudflare workers
- vercel functions
- netflify compute@edge

### Languages

Regular Web App
- Python Django
- PHP Symphony
- Ruby (https://github.com/nov/openid_connect)

Backend/API
- Java (not spring)
- Kotlin

SPA
- Vanilla JS
- Typescript

Native/Mobile App
- iOS Swift (https://appauth.io/)
- Android Native "Java" (https://appauth.io/)
- Android Native Kotlin (https://appauth.io/)
- React Native

### Third Party Tools
- nginx
- apache httpd
- envoy proxy

**Comment by mffap** [comment]
@hifabienne @livio-a @peintnermax @fforootd this is a proposed epic for providing basic examples in each language. The contents is based on our previous discussion and further refinement.

I hope the acceptance criteria and the information provided is sufficient to break down the scope from here out. We should keep the scope initially lean and provide a really quick example app for zitadel auth in the defined languages. We have some examples already but they should be reviewed for gaps to the defined scope.

**Comment by hifabienne** [comment]
@mffap It looks good to me.
I think best would be to make different user stories for each example we want to show.
The easiest would be to make an example for frontend and one for backend. After that we would be able to outsource and show them an example.
In backend I think we should take go. Frontend we can either take the react example from @dakshitha and extend it so what we want in the first phase is included or we take the angular example from @peintnermax

**Comment by ernesto-perez-amigo** [comment]
Hello, 

Could you give higher priority to sdk/doc/examples with projects with the Python language? It is a widely used language and there is only one example with Flask quite coupled to this framework.

Thanks in advance

**Comment by mffap** [comment]
> Hello,
> 
> Could you give higher priority to sdk/doc/examples with projects with the Python language? It is a widely used language and there is only one example with Flask quite coupled to this framework.
> 
> Thanks in advance

@ernesto-perez-amigo what would you like to see beyond Flask? Can you give an example? Happy to take that into consideration.
I was working on a Web-App, but got a bit stuck by an issue in the oidc client, and haven't progressed since.

**Comment by hifabienne** [comment]
First examples of most used frameworks and languages are implemented.
You can find the list here: https://zitadel.com/docs/sdk-examples/introduction

If you miss something, please vote or comment on the discussion:
https://github.com/zitadel/zitadel/discussions/7376
