### ISSUE TITLE
[Epic] integration testing for query side

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#5386]
As a ZITADEL dev, I want to implement integration tests for the `internal/query` and `internal/query/projection` packages so that I get more confident about the changes I made.

```[tasklist]
### Acceptance Criteria
- [ ] Define how data are inserted into the tables before tests
- [ ] Define how the projections get events
- [ ] Implement "before" tests
- [ ] Implement integration tests
```

**Comment by hifabienne** [comment]
hei @adlerhurst can I close this? As @eliobischof is currently investigating in how we want to do our tests?
