### ISSUE TITLE
API: OIDC create Session

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#5468]
As a developer I am able to create an OIDC / SAML session, so I can build my own login on top of ZITADEL.

**Acceptance Criteria**
- [ ] ~~Proxy OIDC/OAuth/SAML Endpoints in the UI~~
- [x] API: Authorize Endpoint #6109 #6117
- [x] API: Get Authrequest by ID #6119
- [x] API: Link Session to Authrequest #6123
- [x] API: Get Callback --> Return CallbackURL with Code #6130
- [x] Mapping of Authorization Request into Session
- [ ] OIDC endpoints are implemented in the backend and are compliant with the standard 
     - [x] Authorization Endpoint
     - [x] Token Endpoint (code flow and refresh token flow: #6130)
     - [ ] ~~well known~~ (no change needed)
     - [x] userinfo #6180
     - [x] introspection #6180
     - [x] revoke #6203
     - [x] end session #6226
     - [ ] device authorization
     - [ ] ~~keys~~ (no change needed)
     - [ ] ~~jwt profile~~ (endpoint does not exist and grant is not UI based)
- [ ] I can send the same informations as I am already able with the current oidc implementation:
      - [ ] login_hint, id_token_hint
      - [ ] prompt: none, login, select_account, create
      - [ ] oidc specific scopes: openid, email, profile, address, offline_access
      - [ ] zitadel scopes: role, roles, org id, primary domain, rolenames, audience, zitadel audience, metadata, ressourceowner, idp id
      - [ ] claims according to our docs: https://zitadel.com/docs/apis/openidoauth/claims: acr, address, amr, aud, auth_time, azp, email, email_verified, exp, family_name, gender, iat, iss, jti, locale, name, nbf, nonce, phone, phone_verified, preferred_username, sub, primary domain, roles, user metadata, ressource owner id, ressourceowner name, ressourceowner domain
- [x] session token can be used for authorization (equivalent to access tokens)  #6180
- [x] new access tokens can be used for authorization of calls to ZITADEL API #6180
 

**Additional Information**
- Linking that an access and id token are based on a session
- 
- Scopes are sent in the authrequest proxied to backend, backend does validate. if not valid scopes remove them, save them to session, frontend interprets what to do with scopes

<img width="857" alt="image" src="https://github.com/zitadel/zitadel/assets/38692350/4b66f845-5c58-479c-b0de-e0a76b3dc720">
https://jamboard.google.com/d/1UR4VPURmLJbHwdsd0W1Zw1eYp1w7UP56JiDvIsOMbos/viewer?f=0

**Comment by livio-a** [comment]
Implementation infos:

redirect to login (client based):
https://github.com/zitadel/oidc/blob/main/pkg/op/auth_request.go#L400-L404

code response / creation (code is created in lib):
https://github.com/zitadel/oidc/blob/main/pkg/op/auth_request.go#L443-L463

auth errors (directly displayed or redirected):
https://github.com/zitadel/oidc/blob/main/pkg/op/error.go#L16-L37

**Comment by hifabienne** [comment]
![Image](https://github.com/zitadel/zitadel/assets/38692350/575e6a3c-e222-4ea9-8d79-b282e8cdf730)

https://jamboard.google.com/d/1UR4VPURmLJbHwdsd0W1Zw1eYp1w7UP56JiDvIsOMbos/viewer?f=1

**Comment by muhlemmer** [comment]
Created a staging branch that we can use as merge target until we are done: https://github.com/zitadel/zitadel/tree/oidc-session-v2

**Comment by livio-a** [comment]
Device Authorization Grant will be handled in a separate issue: #6239
