### ISSUE TITLE
[Epic]: Improve Quality Assurance

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#5856]
This Issue gives a view over all issues that should improve quality assurance. It also includes issues from other repos.

- [ ] https://github.com/zitadel/zitadel/issues/5831
- [ ] https://github.com/zitadel/zitadel/issues/5832
- [ ] https://github.com/zitadel/zitadel/issues/5833
- [ ] https://github.com/zitadel/zitadel/issues/5834
- [ ] https://github.com/zitadel/zitadel/issues/5835
- [ ] https://github.com/zitadel/zitadel/issues/5836
- [ ] https://github.com/zitadel/zitadel/issues/5837
- [ ] https://github.com/zitadel/zitadel/issues/5838
- [ ] https://github.com/zitadel/zitadel/issues/5839
- [ ] https://github.com/zitadel/zitadel/issues/5840
- [ ] https://github.com/zitadel/zitadel/issues/5841
- [ ] https://github.com/zitadel/zitadel/issues/5842
- [ ] https://github.com/zitadel/zitadel/issues/5843
- [ ] https://github.com/zitadel/zitadel/issues/5844
- [ ] https://github.com/zitadel/zitadel/issues/5845
- [ ] https://github.com/zitadel/zitadel/issues/5846
- [ ] https://github.com/zitadel/zitadel/issues/5847
- [ ] https://github.com/zitadel/zitadel/issues/5848
- [ ] https://github.com/zitadel/zitadel/issues/5849
- [ ] https://github.com/zitadel/zitadel/issues/5850
- [ ] https://github.com/zitadel/zitadel/issues/5851
- [ ] https://github.com/zitadel/zitadel/issues/5852
- [ ] https://github.com/zitadel/zitadel/issues/5853
- [ ] https://github.com/zitadel/zitadel/issues/5854
- [ ] https://github.com/zitadel/zitadel/issues/5855
- [ ] https://github.com/zitadel/customer-portal/issues/771
- [ ] https://github.com/zitadel/customer-portal/issues/772
- [ ] https://github.com/zitadel/customer-portal/issues/770
- [ ] https://github.com/zitadel/customer-portal/issues/773
- [ ] https://github.com/zitadel/customer-portal/issues/774
- [ ] https://github.com/zitadel/typescript/issues/6
- [ ] https://github.com/zitadel/typescript/issues/7
- [ ] https://github.com/zitadel/typescript/issues/8
- [ ] https://github.com/zitadel/typescript/issues/9
- [ ] https://github.com/zitadel/typescript/issues/10
- [ ] https://github.com/zitadel/actions/issues/17
- [ ] https://github.com/zitadel/terraform-provider-zitadel/issues/90
- [ ] https://github.com/zitadel/terraform-provider-zitadel/issues/91
- [ ] https://github.com/zitadel/terraform-provider-zitadel/issues/92
- [ ] https://github.com/zitadel/terraform-provider-zitadel/issues/93
- [ ] https://github.com/zitadel/zitadel-charts/issues/85

**Comment by hifabienne** [comment]
@eliobischof Which of these issues should we have a look next?
Are all still relevant or can we close some? 
I would assume that we only have a look at the new apis for now, and leave the old ones out, at the momenet.

**Comment by eliobischof** [comment]
@hifabienne the ZITADEL API prefixed issues in this list don't differentiate between new and old API. Would you rather create separate issues? As they are not really different in their nature, I'd keep them together for consistency.

- I increased the priority of the portal tests, as the portal becomes more and more important.
- I decreased the priority for testing the old login UI
- I Increased the priority of completing any unit/integration tests over any acceptance tests, as this enables us to increase the coverage faster

**Comment by mffap** [comment]
@hifabienne I've created another Epic for the customer portal. Do you want to remove the related sub-issues from this Epic?

**Comment by hifabienne** [comment]
> [@hifabienne](https://github.com/hifabienne) I've created another Epic for the customer portal. Do you want to remove the related sub-issues from this Epic?

yes
