### ISSUE TITLE
Usage Telemetry

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#5889]
As a ZITADEL Business Developer I want to be able to get some usage telemetry from ZITADEL, to know which instances are in use and which are not.

We want to implement a usage telemetry projection in ZITADEL and push the events to a specific endpoint. On start of ZITADEL I want to be able to set if the analytics should be pushed or not. (opt in)

### Acceptance Criteria
- [ ] We have a usage telemetry projection with the following data:
      - Instance ID
      - Instance Creation (datetime)
      - First login to instance (datetime)
      - First project created (Not ZITADEL) (datetime)
      - First application/client created (Not ZITADEL) (datetime)
      - First login to client (Not ZITADEL) (datetime)
      - Instance deletion (datetime)
- [ ] I can add a flag to define if I want to send the analytics data
- [ ] I can add an endpoint where the data should be sent
- [ ] I can define how often the data should be sent
- [ ] The data is pushed to the defined endpoint on the defined iteration time

**Comment by eliobischof** [comment]
# TODO
- [ ] Define Config
- [ ] Early review
- [ ] Implement
- [ ] Final Review
- [ ] Configure Cloud Test
- [ ] Configure Cloud Prod
