### ISSUE TITLE
SMS as Second Factor

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#6057]
As an end user I want to have an SMS code as second factor, so when I log in I get sent a code wich I have to enter, so my account is more secure than only with a password.

**Acceptance Criteria**
- [x] SMS 2fa configuration on login policy is implemented on Instance and Organization
- [ ] The user is able to setup/choose sms as second factor in the login flow when he has to setup a 2fa
- [ ] The user is able to setup sms as 2fa in the profile page
- [ ] When I have setup sms as 2fa I have to enter it in the login flow
- [ ] The phone number for the 2fa is not the same as for the phone number field
- [ ] If a phone number has already been verified for the phone number, I am able to set it up as 2fa
- [ ] When setting up sms as 2fa I receive a code to my number which I have to enter

Depends on, if one time code is implemented sms is only an additional channel: https://github.com/zitadel/zitadel/issues/6100

- [x] Manage Settings: https://github.com/zitadel/zitadel/issues/6204
- [x] Extend Auth API: https://github.com/zitadel/zitadel/issues/6206
- [x] Extend Secret Generators: https://github.com/zitadel/zitadel/issues/6225
- [x] Extend Message Texts: #https://github.com/zitadel/zitadel/issues/6223
- [x] Extend Console User Profile: https://github.com/zitadel/zitadel/issues/6207
- [x] Extend Login: https://github.com/zitadel/zitadel/issues/6205
- [x] Extend Session API: https://github.com/zitadel/zitadel/issues/6224

**Comment by mffap** [comment]
Related Discussion: https://github.com/zitadel/zitadel/discussions/5573

**Comment by hifabienne** [comment]
Rough estimation about 10days
