### ISSUE TITLE
Performance Optimization Query Side

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#6306]
With the issue #5031 we optimise the performance on the write side of ZITADEL. After this has been merged, we want to further optimize the query side of ZITADEL. With query side the Get By ID and Search Requests are meant.

**Tasks**
- [ ] Identify which queries have to be optimzed first
- [ ] Identify how we can optimze by id queries
- [ ] Identify how we can optimize search queries
- [ ] Do refactoring

**Comment by hifabienne** [comment]
@adlerhurst @stebenz can you have a look at this issue and estimate it?
I guess as we have the eventstore merged this will be the next one?

**Comment by adlerhurst** [comment]
There are multiple stages of possible improvements.

I would start with the ones which are the most pressing.

With 2.39.1 we optimized `eventstore.FilterToReducer` and deprecated `eventstore.Filter`. Therefore I would start to implement the `eventstore.QueryReducer` interface on `query`-package objects. As soon as we gathered some learnings I would start to rethink the `query/projection`-package in general. There are multiple use cases to consider:

- **By id calls**: The aggregate and the aggregate id are known.
- **List queries**: Only aggregate types and event types are known for the query.
- **Subset of aggregate**: There are by id queries which query a subset of the aggregate, for example application is part of the project aggregate.
- **Right fold queries**: Queries which are only interested in the most recent events

Wording introduced in the [eventstore doc](https://docs.google.com/document/d/1mBq610lxduM0kD1H3PrG7ESBVSYtv_bAq0uYT5alIJw/edit?usp=sharing) to describe lifetime of a projection:

- cache: volatile, can be created for a single request
- shared cache: disposable, but should not be the goal, as it's shared with multiple ZITADEL pods
- storage: non volatile

Wording introduced in the [eventstore doc](https://docs.google.com/document/d/1mBq610lxduM0kD1H3PrG7ESBVSYtv_bAq0uYT5alIJw/edit?usp=sharing) cost of a projection:

- low cost projection: user by id, project by id
- high cost projection: users list, reporting cases, user search

## Improve ByID queries

With the current state of the eventstore we can start to get rid of the `Trigger`-calls on query side by replacing them with `eventstore.Filter`-calls and implement `eventstore.QueryReducer` on the objects. The following list shows which queries can be changed:

- `(*Queries).AppByProjectAndAppID`: possible, make sure that only events of the application are reduced
- `(*Queries).authRequestByIDQuery`: possible
- `(*Queries).Instance`: possible
- `(*Queries).OrgByID`: possible
- `(*Queries).ProjectByID`: possible
- `(*Queries).SessionByID`: possible
- `(*Queries).PersonalAccessTokenByID`: possible
- `(*Queries).GetUserByID`: possible but many events because the login names use multiple aggregates
- `(*Queries).GetNotifyUserByID`: possible but many events because the login names use multiple aggregates
- `(*Queries).GetUser`: possible but many events because the login names use multiple aggregates
- `(*Queries).GetNotifyUser`: possible but many events because the login names use multiple aggregates
- `(*Queries).GetUserMetadataByKey`: possible with some filtering
- `(*Queries).IDPTemplateByID`: difficult, because idp template is no aggregate
- `(*Queries).IDPByIDAndResourceOwner`: difficult, because idp template is no aggregate
- `(*Queries).LockoutPolicyByOrg`: difficult, because idp template is no aggregate
- `(*Queries).LoginPolicyByID`: possible, because there is only one policy on a org and instance
- `(*Queries).NotificationPolicyByOrg`: possible, because there is only one policy on a org and instance
- `(*Queries).DefaultNotificationPolicy`:possible, because there is only one policy on a org and instance
- `(*Queries).PasswordAgePolicyByOrg`: possible, because there is only one policy on a org and instance
- `(*Queries).DefaultPasswordAgePolicy`: possible, because there is only one policy on a org and instance
- `(*Queries).PasswordComplexityPolicyByOrg`: possible, because there is only one policy on a org and instance
- `(*Queries).DefaultPasswordComplexityPolicy`: possible, because there is only one policy on a org and instance
- `(*Queries).PrivacyPolicyByOrg`: possible, because there is only one policy on a org and instance
- `(*Queries).DefaultPrivacyPolicy`: possible, because there is only one policy on a org and instance
- `(*Queries).ProjectGrantByID`: possible, but all events of the project have to be reduced for filtering
- `(*Queries).GetAuthNKeyByID`: difficult, because multiple aggregates which could lead to many events
- `(*Queries).GetOrgMetadataByKey`: possible, all events of org must be reduced
- `(*Queries).SearchOrgMetadata`: search so impossible, search is implemented in sql
- `(*Queries).SearchProjectRoles`: search so impossible, search is implemented in sql
- `(*Queries).UserGrant`: search so impossible, many aggregates
- `(*Queries).UserGrants`:  search so impossible, many aggregates, search in sql
- `(*Queries).Memberships`: search so impossible, many aggregates, search in sql
- `(*Queries).SearchUserMetadata`: search so impossible, search is implemented in sql

There were some experiments for by id calls which might be helpful:

- https://github.com/zitadel/zitadel/compare/main...pervormance-user
- https://github.com/zitadel/zitadel/compare/main...projection-without-storage

## List queries

List queries are different from by id calls because we don't have enough information and the client might want to filter by a payload field. So we need to maintain a list which is easy to query.

Currently the following executed in scheduled jobs:

1. Query instances which created events within a configured time frame
2. Query and lock the current state of the projection
3. Query events newer than the current state for a specific instance
4. Reduce events
5. Write events to projection table
6. Update and unlock current state
7. Continue with next instance

There are multiple possible problems within these steps:

1. Difficult request and hard to optimize
2. blocks all reads of the current state of the projection for an instance, this causes unnecessary waiting times
3. and 4. use the deprecated `eventstore.Filter` method, this change would not take too much time

We should consider other options there.

## Aggregate design

With the new API's we started to divide aggregates to smaller separate ones with a smaller event count per aggregate id. Mostly it's possible to calculate the amount of expected events per id.

Nonetheless we should evaluate the currently existing aggregates, there are aggregate id's with too many events.

Additionally we should get a better understanding when to create new aggregates or not, document the current aggregates and create a vision which aggregate- and event types will be added next.

## Implement Filter in eventstore/v3 package

The new eventstore/v3 package currently only implements the `eventstore.Pusher`-interface. We should design a proper implementation for Filter so that we can face out the eventstore/repository package.

I suggest to rethink the `SearchQueryBuilder` as well. I think a struct might fit our requirements better.

The implementation should consider to use as few allocs as possible.

**Comment by muhlemmer** [comment]
We have a number of event types that have an `Expiry` property. If we want the query the eventstore directly it would be helpful to exclude expired events. Some examples:

- Token
- Key pairs

Some ideas:

1. Add an `expiry` column which may be null and include it in an index
2. Index the  JSON expiry key directly, if such a thing is possible with Go formatted timestamps from `json.Marshal`

**Comment by muhlemmer** [comment]
When using the event store directly, it would be great in the Query Builder is capable of producing CTE queries where the `owner` column output can be used a `aggregate_id` input without requiring to send a double query. For example for the introspection endpoint I would need:

```sql
with user_events as (
	select * from eventstore.events2
	where instance_id = '230690539048009730'
	and aggregate_type = 'user'
	and aggregate_id = '230690539064852482'
	and event_type in ('user.human.added', 'user.human.email.verified')
), owner_events as (
	select * from eventstore.events2
	where instance_id = '230690539048009730'
	and aggregate_type = 'org'
	and aggregate_id = (select distinct owner from user_events)
	and event_type in ('org.added', 'org.domain.primary.set')
)
select * from user_events
union all
select * from owner_events
ORDER BY instance_id ASC, aggregate_type ASC, aggregate_id ASC, sequence ASC;
```

**Comment by elinashoko** [comment]
Closing as won't be needed with our new upcoming database.
