### ISSUE TITLE
Bug: Change Domain Policy when to many Users

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#6451]
At the moment changing the suffix username attribute is not possible to change if the request takes longer than a certain time. This happens when the organization has to many users and they all have to be changed.

**Accaptance Criteria**
- [ ] It should be possible to change the attribute no matter how many users an org has.
- [ ] The change of the users is handled async in the background
- [ ] I am able to start the change end get an endpoint back, where I can get the state of the execution
- [ ] I have an endpoint where I can get the state of the task
- [ ] The state returns how many users are done, and how many are missing (e.g 500/1225)
- [ ] The state returns a list of users that couldn't be changed, and also the error/info why that user couldn't be changed

**Comment by adlerhurst** [comment]
# Task API

## Overview

ZITADEL provides functionality which is not possible to handle in standard request response methology because the background operations take too much time or the amount of data sent which needs to be processed is too big.

The following list provides a not final list of such functionality:

- Import (e.g. users)
- Create roles
- Grant users access to a project
- Change policies which have impact on multiple objects (e.g. change domain policy)

The above list can be split into two different cases:

1. Manipulate multiple objects (e.g. import)
2. Manipulate a single object (e.g. policy) which results in side effects

In the 1. case the client sends a batch of data is received by ZITADEL. These calls can also be fullfilled by calling the same endpoint many times.  
In the 2. case the data received can be a single field of payload but manipulates many objects in background.  
They both result in long running operations which should execute asynchronoously and allow the user to track the state of the request.

It's currently assumed that both cases result in applying the same operations to many objects, therefore the cases are summarized to **bulk operations**.

### Problem

Currently there are **synchronous** API methods like [Bulk Add Project Role](https://zitadel.com/docs/apis/resources/mgmt/management-service-bulk-add-project-roles) or [Reset Domain Settings of Organization](https://zitadel.com/docs/apis/resources/admin/admin-service-reset-custom-domain-policy-to-default). 

And **asynchronous** API methods like [Import data](https://zitadel.com/docs/apis/resources/admin/admin-service-import-data) or [Export data](https://zitadel.com/docs/apis/resources/admin/admin-service-export-data)

#### Synchonous methods

**Pro's**

- Single call to the API
- All or nothing operation

**Cons's**

- Can time out which can lead to
  - User can't execute operation at all
  - User has to execute a different call which executes the operation one by one (e.g. Add Project Role) which leads to rate limits or additional costs
- Connection is hold open until the request finishes
- Client has no overview of the state of the operation
- Huge work load in a single transaction because many data must be read and manipulated

#### Asychronous methods

**Pro's**

- Single call to the API
- User can query state of operation
- No timeout of a single call

**Cons's**

- User has to call a different method to check the state of an operation
- Operation can lead to inconsistent state (e.g. not all users created)

#### Conclusion

Because there are different patterns used it's difficult for users to understand how they have to use the APIs and react to responses. And ZITADEL is currently not able to fulfil all the requirements requested by users.

The current implementation of the synchronous methods can cause unusable API methods because operation never fulfill before calls time out. On the other hand asynchronous methods can lead to inconsistencies because it was not possible to execute all the operations.

## How do others solve the problem?

### Resource based

Zendesk provides an endpoint per resource to batch calls. For example [create many users](https://developer.zendesk.com/api-reference/ticketing/users/users/#create-many-users) and returns a [job](https://developer.zendesk.com/api-reference/ticketing/users/users/#example-responses-9). They limit the endpoint to 100 objects per call and you have to contact their support to enable the endpoint.

Their thoughts are described in this [blog post](https://developerblog.zendesk.com/from-100-requests-to-1-introducing-our-new-bulk-and-batch-apis-a5bb294e2132).

The job object feels quite natural to me. You get an overview of the state of the operation and can also inspect the details of each object manipulated.

### Multiple operation types

Google provides a general endpoint to bulk multiple requests to a sinlge request as described in [this guide](https://developers.google.com/drive/api/guides/performance#details). This allows to manipluate different objects in the same requests.

As you can send different operations and objects you gain a lot of flexibility but the request can get very complex. You can also configure the response but this also feels like a lot of mental overhead.

## Conclusion

It looks to me that providing async bulk operations provides huge value to the API users. It solves many of the problems at bigger scale or during migration scenarios where bigger amounts of data are transfered or the user has to call the API many times. There are also operations in ZITADEL which take longer as "Reset Domain Settings of Organization" mentoned earlier.

Nonetheless there are some remaining unclarities on my side:

- Must a user be able to cancel a bulk operation?
  - What should happen if they cancel the operation?
- Should we allow external data sources (e.g. a json file located on a s3 storage)?
- How should we store the operations internally? 
  - Do we store them to a seperate table in the database?
- When do we validate the data?
- How should we provide a status if the object has no unique identifier?
- How long should we store operation (detail) results?
- How long should we store the requested operations?
- What are the results if there are other objects changed during the operation (e.g. "Reset Domain Settings of Organization")
- How to handle pagination of the operation details?
- How to display in console?
- Where should we break the API?

## Personal opinion

Based on the current knowledge, I'd prefer the resource based approach because

- it feels like it's easier to understand for API users
- ZITADEL has better control about the operations which are possible to bulk
- Types of request and response objects are static

## Additional thougts

The approach could also be used to export data.

## Additional infos

interesting article about this problem: https://tyk.io/blog/api-design-guidance-bulk-and-batch-import/

**Comment by hifabienne** [comment]
This should have improved with the latest eventstore changes, I will close it for now.
Will reopen if we get problems again in the future

**Comment by meowwwdev** [comment]
Hi @hifabienne , this issue still persists. I am using ZITADEL Cloud with ~10k users and am encountering a timeout after 15 seconds. Could you please reopen the issue?

<img width="375" height="83" alt="Image" src="https://github.com/user-attachments/assets/3ed7f729-aa9e-44fb-9858-c02811403c6a" />

**Comment by adlerhurst** [comment]
Hi there

Thanks for the input. We will investigate this issue within the move to relational tables (v5).
