### ISSUE TITLE
eventstore ongoing work

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#6461]
- [x] global ordering
  - [x] new column `position`
  - [x] new "private" column `commit_order` => renaming missing
- [x] performance (indexes)
- [x] new handler (scheduled and pubsub)
  - [x] failed events
  - [x] move `current_sequences` to `current state`
- [x] fix failing tests
- [x] postgres implementation
- [x] test it with production like load
- [x] projection fluid bulk load on timeouts
- [x] split setup sql files into separate ones per statement
- [x] migration for old events

```[tasklist]
### Tasks
```
