### ISSUE TITLE
General Confusion around Organization Domains

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#6554]
We do have different domain in ZITADEL, one is the "custom domains" that can be configured within ZITADEL. The other are the organization domains, which are used for domain discovery and in some cases to suffix the users.

The naming should be consistent and text really clear about what it is. Also the UI should be improved to make it more understanable.

**Acceptance Criteria**
Custom Domains:
- [x] User Term "Custom Domains" where ever the domain on which ZITADEL is hosted, is meant.

Org Domains:
- [x] Modal to verify the organization domain is shown, no matter if the verification is enabled or not: https://github.com/zitadel/zitadel/issues/6545
- [x] Per default the manual verification of an organization domain should be disabled: https://github.com/zitadel/zitadel/issues/6546
- [x] Rename "Validate Org Domains" on the domain settings to "Verify organization domains with ACME challenge (DNS or HTTP)"
- [x] Org Owner should not see domain settings https://github.com/zitadel/zitadel/issues/6547
- [x] Change Side Menu in the Settings and remove Domains from main nav: https://github.com/zitadel/zitadel/pull/6612
       Domain Discovery: 
        - Settings 
        - Domains

**Comment by peintnermax** [comment]
The org settings are moved to the organization settings with https://github.com/zitadel/zitadel/pull/6612
