### ISSUE TITLE
Onboarding Flow with Milestones

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#6707]
At the moment the onboarding flow in the management console uses the events API, to figure out which steps already have been done.
In the ZITADEL backend, we already have implemented milestones for that use case.
ZITADEL Console should use the milestones instead of the events search.

**Acceptance Criteria**
- [ ] Milestones are possible to access per API (new APIs)
- [ ] Tests are implemented
- [ ] Console uses milestones endpoint instead of events search

**Comment by hifabienne** [comment]
@peintnermax @eliobischof can you have a look at the estimation?
