### ISSUE TITLE
Optimize Token endpoint

### ISSUE THREAD

**Issue by muhlemmer** [zitadel/zitadel#6808]
Through metrics we have observed that there is room to improve the `oauth/v2/token1` endpoints. The way that the OIDC library was defining interfaces, there are cases where there are redundant database calls. Furthermore, we use standard getter queries such as `GetUserByID` which probably return too much data for the specific request being made.

**Acceptance criteria**
- [ ] No redundant database queries
- [ ] Use specialized queries or single WriteModel where possible
- [ ] < 100 ms 99 percentile. (??)
- [ ] By implementing the following oidc Server methods (grant types):
```
	CodeExchange(context.Context, *ClientRequest[oidc.AccessTokenRequest]) (*Response, error)
	RefreshToken(context.Context, *ClientRequest[oidc.RefreshTokenRequest]) (*Response, error)
	JWTProfile(context.Context, *Request[oidc.JWTProfileGrantRequest]) (*Response, error)
	ClientCredentialsExchange(context.Context, *ClientRequest[oidc.ClientCredentialsRequest]) (*Response, error)
	DeviceToken(context.Context, *ClientRequest[oidc.DeviceAccessTokenRequest]) (*Response, error)
```

Observing metrics the following endpoints are most-used and have priority:

1. `CodeExchange`
2. `RefreshToken`
3. `ClientCredentialsExchange`

### Common code-paths
- [x] #6881
- [x] #6882
- [x] #6883

### ClientCredentialExchange

- [x] #6884

**Comment by hifabienne** [comment]
@muhlemmer @adlerhurst  Would it be possible to estimate this before we plan the next sprint?

**Comment by muhlemmer** [comment]
Changed to epic type and I will create estimated issues for the sub-tasks now.

**Comment by hifabienne** [comment]
@muhlemmer can we close this as all of the subtasks are done?
