### ISSUE TITLE
[Epic]: Impersonation

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#7208]
### Discussed in https://github.com/zitadel/zitadel/discussions/7070

<div type='discussions-op-text'>

<sup>Originally posted by **livio-a** December 13, 2023</sup>
There have been various discussions and requests for ZITADEL to provide an impersonation functionality, resp. to get a token for a user without the need to have him sign into ZITADEL before.

This discussion summaries the previous public and internal discussions and presents the possible implementations.
  It also aims to collect feedback on those (in a single place) in order to make a decision on the preferred solution, resp. be able to prioritize the implementations.

## Resources

- https://github.com/zitadel/zitadel/discussions/6006
- https://github.com/zitadel/zitadel/discussions/5895
- [Impersonation for embedded SDK with ZITADEL | ZITADEL Docs Draft](https://docs-git-mpascenariosdk20231017-zitadel.vercel.app/docs/guides/solution-scenarios/embedded-sdk#configuration)

## Use Cases
- view end  user screen
  - in support scenarios
  - testing (during development)
- use external authentication (e.g. access_token) to authenticate in ZITADEL and retrieve tokens (STS)
  - embedded SDKs in (mobile) apps or web applications inside 3rd party applications, where the user authenticates the app using some 3rd party provider and the SDK needs to be able to get some sort of security token of ZITADEL (e.g. access_token) to call its backend

## Solution Design

Regardless of the use case mentioned above, the application needs to be able to exchange some (external) security token to a new security token for the requested user issued by ZITADEL.

### Token Exchange / Security Token Service (STS)
Security tokens, which want to be exchanged can be issued by two source:
- internal (ZITADEL)
- external (3rd party authorization server / openid provider / … )

#### Internal tokens
Typical cases for exchange of internal tokens are classical impersonation cases like support or test scenarios, where an admin or privileged user needs to get a security token of another user.
- [ ] caller (user) needs permission to exchange his token for a new token
  - [ ] ZITADEL provides a mechanism to allow this, e.g. by (internal) role

#### External tokens
ZITADEL needs to be able to verify external security tokens, e.g. access_tokens of 3rd party authorization servers / openid providers. Furthermore the exchange needs to be limited to trusted issuers.
- [ ] List of allowed issuers
  - [ ] public id (e.g. OIDC issuer, SAML entity id)
  - [ ] endpoint to use for validation (e.g. OAuth Token Introspection)
  - [ ] this endpoint needs to return at least information about the authorized user (e.g. sub claim)
- [ ] caller (application / service user) needs permission to exchange external tokens
  - [ ] ZITADEL provides a mechanism to allow this, e.g. by (internal) role for service user

We identified two implementation options and would like to get some feedback on those and the communities preference:
 - [OAuth2 Token Exchange (RFC 8693)](https://github.com/zitadel/zitadel/discussions/7070#discussioncomment-7838722)
 - [Extension of the Session API](https://github.com/zitadel/zitadel/discussions/7070#discussioncomment-7838731)
</div>

**Comment by mffap** [comment]
+1 from a inbound. The use case here is again support staff impersonating users on an application. 

Having user consent would be ideal, but not mandatory. However audit log must be transparent. 

An additional safeguard, which I find quite useful is to send notifications when a user is impersonated. This would work like our password change notification.
I will open a follow-up improvement issue for this.

@livio-a Interesting insight / idea re privileged actions within the application. They do step-up auth via a custom scope for some high-risk actions (eg, large money transactions). These custom scopes should be blocked for impersonation

**Comment by mffap** [comment]
+1 inbound. The use case is support staff impersonating users to help them resolve issues.

**Comment by mffap** [comment]
+1 from a client call. Service provider wants to use this for support cases.

We should think about consent:
- A global setting to enable/disable
- A global setting to allow organizations to overwrite impersonation 
- Organization setting to enable/disable impersonation for their org
