### ISSUE TITLE
[Epic]: Actions v2 - Extend ZITADEL with custom executions and triggers

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#7235]
# Actions v2

This feature allows further customization of ZITADEL. The admin will be able to provide an endpoint to manipulate the request before zitadel handles a request, manipulate the response before it's sent to the client, react on events which were stored or hook into predefined trigger points to complement a token for example.

The custom code is a REST API server managed by the customer, ZITADEL will call the provided endpoint and either use the HTTP status code of the response or even the response body depending on your configuration.

Examples of configurations and diagrams can be found [in this comment](https://github.com/zitadel/zitadel/issues/7235#issuecomment-1899949453)

This epic summarises the action items for the new actions features. Based on the ["Future of Actions"](https://github.com/zitadel/zitadel/discussions/6926)-Discussion

## Future Tasks

Tasks which are not yet planned but will come up in the future.

### Secure call

This milestone will add security to actions. The goal is to allow the server to verify if the call was made by ZITADEL.

- [x] Sign calls to actions for call verification
  - analog to https://stripe.com/docs/webhooks#verify-manually

### API contract

This milestone adds API contracts to actions, this allows easier implementation of actions because of defined contracts. There are also generators for many languages which allows code generation of the server for your language.

- [ ] move events to proto definitions
- [ ] Create proto which ZITADEL is using as client and action implementation as server
  - [ ] Proto compiler to create proto from services
    - [ ] On request
    - [ ] On response
  - [ ] Proto compiler to create proto from events
  - [ ] Proto compiler to create stubs
    - [ ] ZITADEL action client
    - [ ] Language action server
- [ ] create openapi definition

### SDKs

SDKs allow easy implementation of actions. A developer should only implement the handler and the SDK starts the server to listen to events.

- [ ] define languages to provide an SDK

#### Per language

If possible extend the already existing SDK

- [ ] Implement REST server
  - [ ] overwrite default path path
- [ ] Provides endpoint per trigger
  - [ ] Generate endpoints from proto
  - [ ] Allow custom implementation of handler
  - [ ] If possible: automatic protoc after change in ZITADEL
- [ ] Verify signature from ZITADEL
  - analog to https://stripe.com/docs/webhooks#verify-manually

# Targets

The object describes how ZITADEL interacts with the action.

* **id**: uid
* **name**: unique name of the target (e.g. ip_allow_list)
* **type**: one of the below options
  * `REST webhook`: Only response status is used by ZITADEL, response payload is ignored
    * **InterruptOnError**: if false errors are ignored and flow is continued
  * `REST call`: response status and payload are used. The payload is used to manipulate the object
    * **InterruptOnError**: if false errors are ignored and flow is continued
  * `Async`: Asynchronous call, response and payload is ignored, errors are logged
* **endpoint**: URL to the REST POST endpoint
* **timeout**: duration until ZITADEL cancels the query

Response codes of the action are handled as follows:

- successful: >= 200, < 300
- follow redirect: >= 300, < 400
- failure >= 400

Targets can be managed with the following calls:

* **CreateTarget**: adds a new target
* **UpdateTarget**: allows manipulation of the target
* **DeleteTarget**: removes the target, the target will also be removed from requests/responses/functions/events

# Request execution

It's possible to set the following conditions:

- each proto method (e.g. /zitadel.user.v2beta.UserService/AddHuman)
- each proto service (e.g. zitadel.user.v2beta.UserService)
- all requests

ZITADEL decides which condition is triggered like a proxy, the most exact match is executed. A condition is allowed once per instance.

* **condition**: enum value analog conditions above
* **targets**: ordered list of one of the following types
  * **target**: id of a predefined target
  * **include**: id of another condition

Requests can be managed with the following calls:

* **SetRequest**: Creates or updates a request execution for the specified condition, there can only be one request object per condition

# Response execution

It's possible to set the following conditions:

- each proto method (e.g. UserService.AddHuman)
- each proto service (e.g. UserService)
- all requests

ZITADEL decides which condition is triggered like a proxy, the most exact match is executed. A condition is allowed once per instance.

* **condition**: enum value analog conditions above
* **targets**: ordered list of one of the following types
  * **target**: id of a predefined target
  * **include**: id of another condition

Responses can be managed with the following calls:

* **SetResponse**: Creates or updates a response execution for the specified condition, there can only be one response object per condition

# Function execution

It's possible to set the following conditions:

- analog actions v1

The condition only allows exact match. A condition is allowed once per instance.

* **condition**: enum value analog conditions above
* **targets**: ordered list of one of the following types
  * **target**: id of a predefined target
  * **include**: id of another condition

Functions can be managed with the following calls:

* **SetFunction**: Creates or updates a function execution for the specified condition, there can only be one function object per condition

# Event execution

ZITADEL decides which condition is triggered like a proxy, the most exact match is executed. A condition is allowed once per instance.
ZITADEL sends events in the order they occurred and uses the same logic as for internal projections to execute the calls to the targets, including timeouts, failure handling, retries.

* **name**: name of the item
* **condition**: event type or event type group (e.g. user.added, user.*, *)
* **targets**: ordered list of one of the following types
  * **target**: id of a predefined target of type webhook
  * **include**: id of another condition

Events can be managed with the following calls:

* **SetEvent**: Creates or updates a event execution for the specified condition, there can only be one function object per condition

**Comment by adlerhurst** [comment]
# Examples

## Show case

```mermaid
sequenceDiagram
    actor Client
    Client->>+ZITADEL: Create User
    ZITADEL->>ZITADEL: Get request execution for create user
    ZITADEL->>+AddMetadataToUser: request info
    AddMetadataToUser->>AddMetadataToUser: Add metadata
    AddMetadataToUser-->>-ZITADEL: updated user, ok
    ZITADEL->>ZITADEL: Store events
    ZITADEL->>ZITADEL: Get execution for "user.added" event
    ZITADEL->>+UserAddedHook: event (background processing)
    UserAddedHook->>LDAP: Store new user
    UserAddedHook-->>-ZITADEL: ok
    ZITADEL->>ZITADEL: Get response execution for create user
    ZITADEL->>+ResponseStateAsyncHook: response info
    ZITADEL->>-Client: ok
    ResponseStateAsyncHook->>-ResponseStateAsyncHook: Log user id
```

## configuration

```yaml
requests:
  all_requests:
    targets: 
      - target: logger
      - target: allow_list
  user_service:
    targets: 
      - include: all_requests
      - target: call_counter
  change_user:
    targets: 
      - target: all_requests
  add_user:
    targets:
      - target: set_display_name
      - include: all_requests
      - include: user_service

responses:
  all_responses:
    targets: 
      - target: hook
  user_service:
    # hook is called twice in this example
    targets: 
      - include: all_responses
      - target: hook
  change_user:
    targets:
      - include: all_responses
      - target: hook
  add_user:
    targets:
      - include: user_service
      - target: hook

events:
  - name: milestones
    targets:
      - target: handler
      - target: queue
    condition: 
      - project.*
  - name: users
    # only webhooks allowed
    targets:
      - target: webhook1
      - target: webhook2
    events:
      - user.added

function:
  create_id_token:
    targets: 
      - target: hook

targets:
  allow_list:
    # response is not mapped to object
    # only status code is relevant
    type: webhook
    url: https://my.super.duper/endpoint/ip/allow/list
    timeout: 10s
    # returns an error if status code is >= 400
    allow_to_fail: false
    async: false
  allow_list_ignore_err:
    type: webhook
    url: https://my.super.duper/endpoint/ip/allow/list
    timeout: 10s
    allow_to_fail: true
    # awaiting http status
    async: false
  call_counter:
    type: webhook
    url: https://my.super.duper/endpoint/count/calls
    async: true
    timeout: 1s
    allow_to_fail: false
  logger:
    # response is NOT mapped to object
    type: webhook
    url: https://my.super.duper/endpoint/logger
    # NOT waiting for response
    async: true
    # allow_to_fail is irrelevant if async is true
    allow_to_fail: true
  set_display_name:
    # waiting for response
    # response is mapped to object
    type: request response
    url: https://my.super.duper/endpoint/users/displayname
    allow_to_fail: false
    timeout: 1s
```

**Comment by hifabienne** [comment]
https://github.com/zitadel/zitadel/issues/7025

**Comment by vs-gtadeu** [comment]
@hifabienne, question about this epic: would it enable the management of Actions at the instance level?

We plan to use organizations to represent and isolate customers, but because Actions live at the organization, we would have to manage and duplicate actions thousands of times.

**Comment by adlerhurst** [comment]
Hi @vs-gtadeu 
Actions v2 will come available on org level before we deprecate actions v1. Actions v2 will start on instance level before it comes to org level
