### ISSUE TITLE
Command Side for Users with User Schemas (Create / Delete)

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#7308]
As a ZITADEL Administrator I want to be able to add and remove users that apply to a predefined user schema, so I am able to ensure that my user data is consistent and applies to my standards.

## Acceptance Criteria
- [ ] Feature is behind a feature flag
- [ ] Endpoint to add a new user
- [ ] the user data is filled according to the predefined user schema
- [ ] if user doesn't match the userschema, human readable error message is shown
- [ ] As an admin I am able to create a user with all fields that are defined as writeable by admin
- [ ] As an admin I am not able to create a user with fields that are defined as only writeable/creatable by user itself
- [ ] As an end user I am able to create a user with fields that are defined as writeable/createable by myself
- [ ] As an end user I am not able to create a user with fields that are only writeable by an admin
- [ ] Endpoint to remove an exisiting user.
- [ ] Remove is only possible if user has permission to remove (admin or user itself)

## Todos

- [ ] Create user
- [ ] Remove user

### User Object
* **id**: unchangeble, unique identifier of the system
* **schema**: 
    * **type**: schema type of the user (e.g. human/machine)
    * **revision**: read only, revision of the schema the user was stored the last time (e.g. 4)
* **authenticators**: list of possibilites how a user can authenticate itself. there can be multiple authenticators of the same type
* **contact**: email and phone of the user if provided
* **state**: one of `Active`, `Inactive`, `Locked`, `Deleted`
* **data/profile/traits**: custom fields of a user based on the type (whats the best name for this?)

**Comment by stebenz** [comment]
Depend on #7306 for schema
depend on #7314 for authenticators

Technical estimation:
- user events: 1d
- schema validation: 1d
- unit tests: 1d
- writemodel: 1d
- authenticator validation: 1d
- permissions: 1d

**Comment by hifabienne** [comment]
@eliobischof @stebenz as discussed I split the issue into create/delete and update functions.
Can you please estimate this?

Relates
https://github.com/zitadel/zitadel/issues/7898
