### ISSUE TITLE
create app through npx

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#7390]
As a user of npx I want to create an app in ZITADEL using an npx extension. The extension provides the information to ZITADEL for creating the app.

```[tasklist]
### Tasks
- [ ] create npx cli
- [ ] create console endpoint
- [ ] design flow in console
- [ ] implement flow in console
```

## info

the cli calls an endpoint and provides the following params:

- `type`: framework type (e.g. angular)
- `applicationType`: oidc application type (e.g. web)
- `redirectUris`: oidc redirect uris (e.g. http://localhost:4200/login/callback)
- `postLogoutUris`: oidc post logout uri (e.g. http://localhost:4200/logout)
- `scopes`: list of oidc scopes (e.g. openid,profile)
- `grantTypes`: oidc grant types (e.g. implicit)
- `responseTypes`: oidc response types (e.g. code)
- `authenticationType`: oidc authentication type (e.g. none)
- `frameworks`: list of frameworks the app is using
- `redirectTo`: uri to call after success (e.g. http://localhost:8888)
- `projectId`: optional zitadel project id
- `orgId`: optional zitadel org id
- `appName`: optional zitadel app name

console should send the following parameters to the `redirectTo`-url:

- `clientId`: oidc client id
- `clientSecret`: oidc client secret

**Comment by elinashoko** [comment]
Thanks for filing this issue. As part of an ongoing backlog cleanup, we're closing older `area/console` issues.

We're building a replacement for the Console with significantly better usability, and that's where our focus is right now. As a result, the current Console is planned for deprecation over the next 12 months, and we're not prioritizing fixes or improvements to it in the meantime.

If this is still an active problem for you, let us know in a comment (or reopen the issue) and we'll take another look.

This issue will close in 30 days if there's no further activity.

**Comment by elinashoko** [comment]
Thanks for filing this issue. As part of an ongoing backlog cleanup, we're closing issues that have had no activity in over 12 months.

If this is still relevant, let us know in a comment (or reopen the issue) and we'll take another look.

This issue will close in 30 days if there's no further activity.
