### ISSUE TITLE
Console add description texts to resources

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#7391]
As a user of the console I want to get a better understand of the different objects.

```[tasklist]
### Tasks
- [ ] Define description of the objects
- [ ] Add info box to each site
- [ ] Add link to documentation to read more about it
```

## objects

- [ ] Home
  - [ ] Your onboarding process
        Welcome your first user! Complete the following steps to get your app up and running.
  - [x] each shortcut
       - Documentation: Explore the knowledge base. Access our documentation for answers and deeper insights. 
       - Get started with ZITADEL: Start building with our step-by-step guide. 
       - Quickstarts: Grab our SDKs & samples to jumpstart your IAM integration.
- [ ] Organization (info box)
   - Organizations are the foundation of your IAM structure, housing your projects, users, and access settings.
  - [x] Metadata
     - Extend your data model: Add attributes not covered by the core fields, such as industry, location, etc.
  - [ ] Managers (info box)
     - Managers are the administrators within your organization, granting them access to manage system configurations and user access controls.
- [x] Projects (info box)
  - [x] Owned projects
     - Think of projects as vessels for applications (e.g., web, mobile, API) for efficient access control. Additionally, they allow granting access to other organizations, for self-management.
  - [x] Granted projects
     - While another organization owns these projects, you can access them with the ability to define permission within your own organization.
- [x] Users (info box)
  - Authentication and authorization for different user types is supported. The main differences between human and machine users, also called service users, are the authentication mechanisms.
  - [x] Users
    - [x] Identity providers
    - [x] Metadata
  - [x] Service Users
    - [x] Metadata
- [x] Authorizations (info box)
   - Authorizations define user permissions by combining project, user, and roles.
- [x] Actions (info box)
   - Add custom JavaScript actions to specific events and extend the default behavior. These actions are code snippets that run automatically when the chosen event occurs, giving you control over your process.
- [x] Settings
  - [x] Organization Settings (info box)
     - Configure your organization's settings to fit your unique needs. Any changes you make here will override the default settings.
  - [x] Instance Settings (info box)
    - Set the default settings that will apply to all organizations unless customized otherwise.
  - [x] Login Behavior and Security
    - [x] Login Lifetimes
      - Control login session durations and security checks by configuring the "login lifetimes". For example, setting a password check lifetime of 8 hours will prompt users to re-enter their password after 8 hours of inactivity.
        - [x] Password Check Lifetime: Time after which the user will be prompted to re-enter the password
        - [x] External Login Check Lifetime: Time after wich the user will be prompted to re authenticate with an external account such as Google or Azure AD.
        - [x] Multifactor Init Lifetime: Configure this value to determine when users are prompted to set up multi-factor authentication (MFA) for their account. Setting it to 0 disables the prompt.
        - [x] Second-Factor Check Lifetime: Time after wich the user will be prompted to verify the second factor again.
        - [x] Multi-Factor Check Lifetime: Time after wich the user will be prompted to verify the multi factor again.
    - [x] Advanced => DISCUSS: rename to Login screen behavior
      - [x] Username Password allowed (describe what changes)
         - Disabling this setting removes username/password login, requiring users to log in with external accounts like Google or Azure AD.
      - [x] Register user allowed (describe what changes)
        - Disabling this setting will remove the "register button" from the login ui, and will not allow users to self register.
      - [x] Register organizations allowed (describe what changes)
        - Disabling this setting will disable the "Register Organization" form, and will not allow users to self register an organization. Organization registration is useful in B2B use cases.
      - [x] External IDP allowed (describe what changes)
        - Allow users to user external identity providers such as Google or Azure AD to authenticate themself, instead of using a local user account.
      - [x] Hide Password reset(describe what changes)
        - Enabling this settings will remove the "Reser Password" link from the login ui and not allow user to get a password reset notification.
      - [x] Domain discovery allowed (describe what changes)
        - The domain of the user is recognized when entering the username and will be matched to an organization. E.g user@company-a.com will be matched to Company A. This requires a verified domain on the organization.
      - [x] Ignore unknown usernames (describe what changes)
        - This setting can be enabled, if no error message should be shown if the user doesn't exist. None existing users will get an error that either username or password are wrong after entering the password.
      - [x] Disable login with email address (describe what changes)
        - Allow or disallow users to log in with their e-mail address in addition to the username. Be aware that email log in is only possible if it is unique across the system.
      - [x] Disable login with phone number (describe what changes)
        - Allow or disallow users to log in with their phone number in addition to the username. Be aware that phone number log in is only possible if it is unique across the system.
  - [x] Identity providers (info box)
    - This section empowers you to configure Single Sign-On (SSO), allowing users to access multiple applications with a single login. Choose from popular identity providers (IdPs) like Google, Azure AD, or leverage generic options like OIDC, OAuth, JWT, and SAML for wider compatibility.
  - [x] Password complexity (info box)
    - [x] replace "has" with "must include"
      - Configure the specific password requirements (length, uppercase, lowercase, numbers, symbols) to ensure strong passwords and protect user accounts.
  - [x] Lockout (info box)
  - [x] Notification (info box)
    - Configure on which changes the users should be notified. The text of the message can be changed in the message texts.
  - [x] Verified domains (info box)
    - Verified domains are domain proven to belong to your organization. This domains are required for domain discovery of your users during the login process. 
  - [x] Domain settings (info box)
    - The domain settings offer various options to configure how users interact with your system based on their organization domain. 
    - [x] Organization domain verification required (DNS or HTTP challenge)
      - This setting controls how new domains are added to your organization. When disabled: Domains are automatically verified and added upon submission. When enabled: Domains require verification via DNS or HTTP challenge before adding.
    - [x] SMTP Sender Address matches Instance Domain
      - The sender address configured in the SMTP provider, needs to match the custom domain of the system. 
  - [x] Branding (info box)
    - Customize your login screen with your brand colors, fonts, and logo to create a seamless and recognizable experience for your customers. This helps users feel comfortable and familiar right from the start. 
      Remember to click "Apply configuration" after making your changes. This ensures your users see the updated login screen.
  - [x] Message texts (info box)
    - You can customize each message text sent to your users, for any language supported. Whether it's the email verification or password reset e-mail, you have complete control over the text, sent to your users. The default text is shown as placeholder of the input fields.
    - [x] Describe notification type
  - [x] Login interface Texts (info box)
    - You can customize each message within the login process, for any language supported. Whether it's the username label, password reminder, or multi-factor screen, you have complete control over the text users see. The default text is shown as placeholder of the input fields.
    - [x] Describe screen type
  - [x] Privacy policy (info box)
    - This setting allows you to define the links to your Terms of Service (ToS) and privacy policy documents. These links will be displayed during the self-registration process, ensuring users can easily access and review your legal agreements before creating an account.
  - [x] SMTP Provider (info box)
    - By default, email notifications are sent through a preconfigured SMTP provider to ensure all users receive important messages like account verification. For optimal control and customization, it is recommend to configuring your own SMTP provider, especially when your system transitions to production.
  - [x] SMS/Phone provider (info box)
    - This setting allows you to configure Twilio as your SMS provider for sending verification codes to users during phone number verification.
  - [x] Views (info box)
  - [x] Events (info box)
    - The events reflect the built-in audit trail to track all changes over an unlimited period of time. You can filter the whole events list for your specific needs, such as only a specific resource or event type.
  - [x] Failed events (info box)
    - Events that could not been processed after "n" retries are stored for later handling. This ensures that the projections remain operational by not blocking subsequent events.
  - [x] Languages (info box and desscribe that its drag and drop)
    - [x] This is a list of all available languages and translations. Simply drag and drop any language you don't want to offer to the "Disallow" list, to exclude it from serving to your users.
  - [x] OIDC Token lifetime and expiration (info box)
    - Configure the lifetime of the different OIDC Token types to improve security and enhance user experience. 
    - [x] Tooltip for the tokens:
      - Access Token Lifetime: Control how long users can access resources without re-authenticating (e.g., 1 hour for sensitive actions, 24 hours for routine use).
      - ID token lifetime: Determine how long user information in the ID token remains valid (usually shorter than access token for added security).
      - Refresh Token Expiration (Days): Set the overall lifespan of the refresh token used to obtain new access tokens (e.g., 30 days for mobile apps, 90 days for web apps).
      - Refresh Token Idle Expiration (Days): Define how long a refresh token can remain unused before becoming invalid (shorter than expiration for security, longer for convenience).
  - [x] Secret Generator (info box)
    - Secret generators let you define codes and secrets. You can set the length, character set and expiration. 
    - [ ] Bug: Popup of secret generator type looks not styled
  - [x] Security settings (info box)

basic idea:

![image](https://github.com/zitadel/zitadel/assets/27845747/e43cfd63-0ee4-45da-b149-a2911810d50f)
