### ISSUE TITLE
[perf]: load testing tweaks and findings

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#7639]
During first load tests we had some first findings we need to investigate. The results of the tests can be found in the comments below. 

The tests first create a user per VU (virtual user) and then sign in using username and password. The trends ending with `*_duration` measure the request duration.

Testing setup was localhost mac book pro with M1.

Executed load tests: https://github.com/zitadel/zitadel/pull/7635

Most affecting were the so called "trigger" functions on query side.

During this spike we will investigate clean implementations to deprecate the triggers so that query side does no longer rely on the `current_states`-table.

```[tasklist]
### Tasks
- [ ] Document investigation outcome of load tests
- [ ] Describe possible solutions for the documented problems
- [ ] Try possible solutions
- [ ] Create issues for remaining tasks
```

Estimation: 10 days

Internal information:

Traces can be found here: https://github.com/zitadel/DevOps/issues/29#issuecomment-2022270152

**Comment by adlerhurst** [comment]
200 parallel users:

```bash
INFO[0002] admin signed in                               source=console
INFO[0002] org (259977152257111614) created              source=console
INFO[0044] 200 users created                             source=console

     ✓ user defined
     ✓ authorize status ok
     ✓ login name status ok
     ✓ login shows password page
     ✓ login has no error
     ✓ password status ok
     ✓ password callback
     ✓ code set
     ✓ token status ok
     ✓ access token created
     ✓ openid configuration
     ✓ userinfo status ok

     █ setup

       ✓ user defined
       ✓ authorize status ok
       ✓ login name status ok
       ✓ login shows password page
       ✓ login has no error
       ✓ password status ok
       ✓ password callback
       ✓ code set
       ✓ token status ok
       ✓ access token created
       ✓ org created
       ✓ create user is status ok

     █ teardown

       ✓ org removed

     checks...............................: 100.00% ✓ 13788     ✗ 0    
     data_received........................: 24 MB   94 kB/s
     data_sent............................: 4.4 MB  17 kB/s
     http_req_blocked.....................: avg=7.5ms    min=0s       med=1µs      max=1.1s     p(90)=1µs      p(95)=2µs     
     http_req_connecting..................: avg=4.53ms   min=0s       med=0s       max=1.01s    p(90)=0s       p(95)=0s      
     http_req_duration....................: avg=4.03s    min=6.89ms   med=1.05s    max=33.28s   p(90)=14.58s   p(95)=17.91s  
       { expected_response:true }.........: avg=4.03s    min=6.89ms   med=1.05s    max=33.28s   p(90)=14.58s   p(95)=17.91s  
     http_req_failed......................: 0.00%   ✓ 0         ✗ 10738
     http_req_receiving...................: avg=1.03ms   min=12µs     med=140µs    max=764.87ms p(90)=1.27ms   p(95)=2.3ms   
     http_req_sending.....................: avg=109.54µs min=7µs      med=93µs     max=8.86ms   p(90)=172µs    p(95)=206µs   
     http_req_tls_handshaking.............: avg=2.95ms   min=0s       med=0s       max=483.6ms  p(90)=0s       p(95)=0s      
     http_req_waiting.....................: avg=4.03s    min=5.34ms   med=1.05s    max=33.28s   p(90)=14.58s   p(95)=17.91s  
     http_reqs............................: 10738   42.302557/s
     iteration_duration...................: avg=34.01s   min=530.93ms med=31.34s   max=1m33s    p(90)=56.53s   p(95)=1m6s    
     iterations...........................: 1216    4.790455/s
     login_password_login_duration........: avg=34.03s   min=6.16s    med=31.34s   max=1m33s    p(90)=56.54s   p(95)=1m6s    
     login_ui_enter_login_name_duration...: avg=7.12s    min=273.27ms med=3.27s    max=20.95s   p(90)=17.76s   p(95)=18.77s  
     login_ui_enter_password_duration.....: avg=955.11ms min=6.89ms   med=9.82ms   max=14.76s   p(90)=4.03s    p(95)=8.41s   
     login_ui_init_login_duration.........: avg=1.89s    min=168.51ms med=714.05ms max=21.87s   p(90)=5.97s    p(95)=8.02s   
     login_ui_token_duration..............: avg=7.06s    min=190.71ms med=3.14s    max=20.52s   p(90)=17.42s   p(95)=18.54s  
     oidc_user_info_duration..............: avg=11.27s   min=256.08ms med=9.18s    max=33.28s   p(90)=22.65s   p(95)=24.69s  
     setup_create_org_duration............: avg=100.79ms min=100.79ms med=100.79ms max=100.79ms p(90)=100.79ms p(95)=100.79ms
     setup_create_user_duration...........: avg=10.21s   min=807.44ms med=9.06s    max=22.89s   p(90)=19.87s   p(95)=21.59s  
     vus..................................: 24      min=0       max=200
     vus_max..............................: 200     min=200     max=200


running (4m13.8s), 000/200 VUs, 1216 complete and 0 interrupted iterations
default ✓ [======================================] 200 VUs  3m20s
```

**Comment by adlerhurst** [comment]
150 parallel users:

```
INFO[0002] admin signed in                               source=console
INFO[0002] org (259976343930844734) created              source=console
INFO[0044] 150 users created                             source=console

     ✓ user defined
     ✓ authorize status ok
     ✓ login name status ok
     ✓ login shows password page
     ✓ login has no error
     ✓ password status ok
     ✓ password callback
     ✓ code set
     ✓ token status ok
     ✓ access token created
     ✓ openid configuration
     ✓ userinfo status ok

     █ setup

       ✓ user defined
       ✓ authorize status ok
       ✓ login name status ok
       ✓ login shows password page
       ✓ login has no error
       ✓ password status ok
       ✓ password callback
       ✓ code set
       ✓ token status ok
       ✓ access token created
       ✓ org created
       ✓ create user is status ok

     █ teardown

       ✓ org removed

     checks...............................: 100.00% ✓ 11246     ✗ 0    
     data_received........................: 19 MB   76 kB/s
     data_sent............................: 3.6 MB  14 kB/s
     http_req_blocked.....................: avg=5.59ms   min=0s       med=1µs      max=1.06s    p(90)=2µs     p(95)=2µs    
     http_req_connecting..................: avg=2.83ms   min=0s       med=0s       max=1.01s    p(90)=0s      p(95)=0s     
     http_req_duration....................: avg=3.75s    min=6.32ms   med=1.51s    max=27.11s   p(90)=10.95s  p(95)=14.29s 
       { expected_response:true }.........: avg=3.75s    min=6.32ms   med=1.51s    max=27.11s   p(90)=10.95s  p(95)=14.29s 
     http_req_failed......................: 0.00%   ✓ 0         ✗ 8712 
     http_req_receiving...................: avg=1.58ms   min=12µs     med=140µs    max=1.71s    p(90)=1.34ms  p(95)=3.02ms 
     http_req_sending.....................: avg=116.74µs min=13µs     med=87µs     max=26.95ms  p(90)=175µs   p(95)=215µs  
     http_req_tls_handshaking.............: avg=2.75ms   min=0s       med=0s       max=497.64ms p(90)=0s      p(95)=0s     
     http_req_waiting.....................: avg=3.75s    min=0s       med=1.51s    max=27.11s   p(90)=10.92s  p(95)=14.29s 
     http_reqs............................: 8712    34.594902/s
     iteration_duration...................: avg=30.94s   min=348.97ms med=25.36s   max=1m38s    p(90)=1m6s    p(95)=1m19s  
     iterations...........................: 994     3.947123/s
     login_password_login_duration........: avg=30.96s   min=6.76s    med=25.36s   max=1m38s    p(90)=1m6s    p(95)=1m19s  
     login_ui_enter_login_name_duration...: avg=5.65s    min=393.77ms med=4.21s    max=23.74s   p(90)=9.77s   p(95)=11.71s 
     login_ui_enter_password_duration.....: avg=1.89s    min=6.32ms   med=9.6ms    max=22.31s   p(90)=10.69s  p(95)=14.42s 
     login_ui_init_login_duration.........: avg=2.67s    min=176.03ms med=986.29ms max=27.11s   p(90)=6.48s   p(95)=15.31s 
     login_ui_token_duration..............: avg=4.41s    min=189.69ms med=3.42s    max=13.89s   p(90)=8.56s   p(95)=9.02s  
     oidc_user_info_duration..............: avg=9.49s    min=141.91ms med=9.31s    max=25.23s   p(90)=16.2s   p(95)=17.49s 
     setup_create_org_duration............: avg=96.89ms  min=96.89ms  med=96.89ms  max=96.89ms  p(90)=96.89ms p(95)=96.89ms
     setup_create_user_duration...........: avg=13.01s   min=1.58s    med=12.93s   max=24.34s   p(90)=22.37s  p(95)=23.29s 
     vus..................................: 33      min=0       max=150
     vus_max..............................: 150     min=150     max=150


running (4m11.8s), 000/150 VUs, 994 complete and 0 interrupted iterations
```

**Comment by adlerhurst** [comment]
350 parallel users

```
INFO[0002] admin signed in                               source=console
INFO[0002] org (259979216391554955) created              source=console
INFO[0091] 350 users created                             source=console

     ✓ user defined
     ✗ authorize status ok
      ↳  99% — ✓ 1041 / ✗ 4
     ✓ login name status ok
     ✓ login shows password page
     ✓ login has no error
     ✓ password status ok
     ✓ password callback
     ✓ code set
     ✓ token status ok
     ✓ access token created
     ✓ openid configuration
     ✓ userinfo status ok

     █ setup

       ✓ user defined
       ✓ authorize status ok
       ✓ login name status ok
       ✓ login shows password page
       ✓ login has no error
       ✓ password status ok
       ✓ password callback
       ✓ code set
       ✓ token status ok
       ✓ access token created
       ✓ org created
       ✓ create user is status ok

     █ teardown

       ✓ org removed

     checks...............................: 99.96% ✓ 12167     ✗ 4    
     data_received........................: 25 MB  77 kB/s
     data_sent............................: 4.3 MB 14 kB/s
     http_req_blocked.....................: avg=22.94ms  min=0s       med=1µs     max=1.48s    p(90)=2µs     p(95)=2µs    
     http_req_connecting..................: avg=15.05ms  min=0s       med=0s      max=1.35s    p(90)=0s      p(95)=0s     
     http_req_duration....................: avg=8.31s    min=6.55ms   med=1.95s   max=57.5s    p(90)=27.66s  p(95)=35.44s 
       { expected_response:true }.........: avg=8.3s     min=6.55ms   med=1.94s   max=57.5s    p(90)=27.65s  p(95)=35.44s 
     http_req_failed......................: 0.03%  ✓ 4         ✗ 10092
     http_req_receiving...................: avg=1.46ms   min=0s       med=153µs   max=773.01ms p(90)=1.57ms  p(95)=4ms    
     http_req_sending.....................: avg=132.86µs min=10µs     med=97µs    max=13.31ms  p(90)=192µs   p(95)=243µs  
     http_req_tls_handshaking.............: avg=7.87ms   min=0s       med=0s      max=868.13ms p(90)=0s      p(95)=0s     
     http_req_waiting.....................: avg=8.3s     min=5.8ms    med=1.95s   max=57.5s    p(90)=27.66s  p(95)=35.44s 
     http_reqs............................: 10096  31.727135/s
     iteration_duration...................: avg=1m13s    min=478.87ms med=1m10s   max=2m38s    p(90)=1m57s   p(95)=2m12s  
     iterations...........................: 1045   3.28396/s
     login_password_login_duration........: avg=1m13s    min=5.84s    med=1m10s   max=2m38s    p(90)=1m57s   p(95)=2m12s  
     login_ui_enter_login_name_duration...: avg=16.38s   min=430.65ms med=12.78s  max=38.92s   p(90)=35.05s  p(95)=36.44s 
     login_ui_enter_password_duration.....: avg=2.5s     min=6.55ms   med=10.26ms max=17.19s   p(90)=8.76s   p(95)=9.81s  
     login_ui_init_login_duration.........: avg=4.33s    min=181.27ms med=1.25s   max=27.3s    p(90)=13.8s   p(95)=15.73s 
     login_ui_token_duration..............: avg=15.43s   min=199.12ms med=12.08s  max=38.45s   p(90)=34.44s  p(95)=36.27s 
     oidc_user_info_duration..............: avg=20.35s   min=233.88ms med=18.17s  max=57.5s    p(90)=40.82s  p(95)=42.83s 
     setup_create_org_duration............: avg=82.85ms  min=82.85ms  med=82.85ms max=82.85ms  p(90)=82.85ms p(95)=82.85ms
     setup_create_user_duration...........: avg=21.26s   min=1.32s    med=19.72s  max=46.92s   p(90)=41.6s   p(95)=44.43s 
     vus..................................: 0      min=0       max=350
     vus_max..............................: 350    min=350     max=350


running (5m18.2s), 000/350 VUs, 1045 complete and 0 interrupted iterations
default ✓ [======================================] 350 VUs  3m20s
```

**Comment by adlerhurst** [comment]
machine pat login:

```
INFO[0002] setup: admin signed in                        source=console
INFO[0002] setup: org (260103742139985562) created       source=console
INFO[0052] setup: 400 machines created                   source=console
INFO[0060] setup: Pats added                             source=console
INFO[0274] teardown: org removed                         source=console

     ✓ openid configuration
     ✓ userinfo status ok

     █ setup

       ✓ user defined
       ✓ authorize status ok
       ✓ login name status ok
       ✓ login shows password page
       ✓ login has no error
       ✓ password status ok
       ✓ password callback
       ✓ code set
       ✓ token status ok
       ✓ access token created
       ✓ org created
       ✓ create user is status ok
       ✓ add pat status ok

     █ teardown

       ✓ org removed

     checks...............................: 100.00% ✓ 6253      ✗ 0    
     data_received........................: 9.6 MB  35 kB/s
     data_sent............................: 1.1 MB  3.8 kB/s
     http_req_blocked.....................: avg=51.6ms   min=0s       med=1µs      max=2.33s    p(90)=2µs      p(95)=316.23ms
     http_req_connecting..................: avg=34.53ms  min=0s       med=0s       max=2.02s    p(90)=0s       p(95)=70.87ms 
     http_req_duration....................: avg=12.92s   min=10.03ms  med=13.58s   max=43.38s   p(90)=22.69s   p(95)=25.93s  
       { expected_response:true }.........: avg=12.92s   min=10.03ms  med=13.58s   max=43.38s   p(90)=22.69s   p(95)=25.93s  
     http_req_failed......................: 0.00%   ✓ 0         ✗ 6651 
     http_req_receiving...................: avg=207.19µs min=13µs     med=124µs    max=17.93ms  p(90)=205µs    p(95)=285.49µs
     http_req_sending.....................: avg=111.81µs min=8µs      med=63µs     max=7.64ms   p(90)=145µs    p(95)=273.49µs
     http_req_tls_handshaking.............: avg=17.05ms  min=0s       med=0s       max=2.24s    p(90)=0s       p(95)=50.83ms 
     http_req_waiting.....................: avg=12.92s   min=9.79ms   med=13.58s   max=43.38s   p(90)=22.69s   p(95)=25.93s  
     http_reqs............................: 6651    24.31244/s
     iteration_duration...................: avg=16.35s   min=500.07ms med=16.58s   max=59.23s   p(90)=24.25s   p(95)=26.95s  
     iterations...........................: 5041    18.427155/s
     login_ui_enter_login_name_duration...: avg=324.56ms min=324.56ms med=324.56ms max=324.56ms p(90)=324.56ms p(95)=324.56ms
     login_ui_enter_password_duration.....: avg=10.03ms  min=10.03ms  med=10.03ms  max=10.03ms  p(90)=10.03ms  p(95)=10.03ms 
     login_ui_init_login_duration.........: avg=245.39ms min=245.39ms med=245.39ms max=245.39ms p(90)=245.39ms p(95)=245.39ms
     login_ui_token_duration..............: avg=201.38ms min=201.38ms med=201.38ms max=201.38ms p(90)=201.38ms p(95)=201.38ms
     oidc_user_info_duration..............: avg=16.27s   min=277.16ms med=16.55s   max=43.38s   p(90)=24.14s   p(95)=26.92s  
     setup_create_human_duration..........: avg=5.03s    min=536.22ms med=5.2s     max=8.89s    p(90)=8.21s    p(95)=8.54s   
     setup_create_org_duration............: avg=98.49ms  min=98.49ms  med=98.49ms  max=98.49ms  p(90)=98.49ms  p(95)=98.49ms 
     vus..................................: 3       min=0       max=400
     vus_max..............................: 400     min=400     max=400


running (4m33.6s), 000/400 VUs, 5041 complete and 0 interrupted iterations
default ✓ [======================================] 400 VUs  3m20s
```

**Comment by adlerhurst** [comment]
# Query triggers

The load tests show that so called `triggers` in the query package and `getLatestState` are blocking. If multiple execution paths call the same method of queries which does a `trigger` first they are blocking. 

## Options

Possible mitigation of the problem are the following.

### Move triggers to command side (API)

As the data can only change during a command in CQRS it would be feasible to move the calls of the `triggers` of the projections to the command side and call them during or after a command. 

#### Pros

+ low hanging because the changes on the code are little
+ fast everything already exists, its just moving code

#### Cons

- root cause is not solved
- problem could reoccur including even more parts of the system
- quality is hard to achieve because changes on projections include possible extension of the trigger list of commands

### Remove triggers

Instead of ensuring that the data are up-to-date on the list projections we call the eventstore directly or first query the current data and afterwards the eventstore to reduce the not yet reduced events.  
To fulfill the requirements of the queries the event store interface need to be extended that multiple questions can be answered in a single query.  
The change also includes in memory processing of the events which is currently solved by database DML-queries. This change can reduce times to left fold an object drastically because there are no round trips to the database for each event.

#### Pros

+ solves the actual root cause
+ possible performance improvement of reduce
+ allows future optimizations if needed

#### Cons

- time to implement, however small changes can easily be shipped and hidden behind a feature flag
- many code changes

### Outcome

The issues to improve the oidc server side improve the speed of the oidc endpoints, these optimizations should be prioritized.

As [Option 1](#move-triggers-to-command-side-api) does not solve the root cause we focus on [Option 2](#remove-triggers) verify this approach. If the outcome is as expected create issues for each query method which uses `triggers` and prioritize them as high.

## Additional work

As the session-resource gets more important we need additional load tests for this part of zitadel. This could result in additional issues including the auth middleware of zitadel.

**Comment by adlerhurst** [comment]
# Improvement of app and project queries

## Test

Mac M1 

`VUS=100 ADMIN_PASSWORD=Test111$ DURATION=300s make machine_pat_login`

## Before

Branch: main

| Percentile | Latency |
| --- | ----: |
25% | 64 ms
50% | 1485 ms
75% | 1924 ms
90% | 2233 ms
95% | 2361 ms

## After

PR: https://github.com/zitadel/zitadel/pull/7817

| Percentile | Latency |
| --- | ----: |
25% | 16 ms
50% | 49 ms
75% | 501 ms
90% | 1335 ms
95% | 1426 ms

**Comment by adlerhurst** [comment]
# latency of token endpoint

## Test

Mac M1 

`VUS=100 ADMIN_PASSWORD=Test111$ DURATION=300s make human_password_login`

Limit db connections to 100

## Before

Branch: main

| Percentile | Latency |
| ---: | ----: |
25% | 7 ms
50% | 21 ms
90% | 3565 ms
95% | 3796 ms
99% | 4120 ms
99.5% | 4409 ms

## After

PR: https://github.com/zitadel/zitadel/pull/7817

| Percentile | Latency |
| ---: | ----: |
25% | 18 ms
50% | 48 ms
90% | 1641 ms
95% | 2000 ms
99% | 3266 ms
99.5% | 5023 ms

**Comment by adlerhurst** [comment]
closing this because tasks are either resolved or defined other issues.
