### ISSUE TITLE
Proto definitions

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#7650]
As an API designer, I want to have all endpoints and options clearly defined, so I can ensure consistency and challenge the design with the community and with customers.

### Acceptance Criteria
- [ ] The whole API is defined as proto according to #7592 and #7649
- [ ] The docs from #7649 are updated according to new learnings
- [ ] The API Guidelines from #7592 are updated according to new learnings
- [ ] Subissues defined with #7649 are updated according to new learnings

**Comment by hifabienne** [comment]
This will be closed as we have explicit issues for each part of the resources
