### ISSUE TITLE
Improve Execution objects of execution api

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#7669]
The goal of this issue is to improve the structure of the execution/v3alpha service.

Currently `Execution`-message does not represent the order of the execution list as targets and includes are separated into two fields. We propose to unify the the fields into a single one to represent the order.

Additionally we want to discuss the specific execution objects like `RequestExecution`. The hierarchy of request, response and event is currently not clearly stated and therefore makes it complex to fully understand the API. The proposal includes a strategy to display the hierarchy to the API client. 

An overview of the [proposed changes](https://github.com/zitadel/zitadel/blob/proposal-execution-target/proto/zitadel/execution/v3alpha/execution.proto) can be found in [this PR](https://github.com/zitadel/zitadel/pull/7666).

The proposal would also allow to use enums instead of strings which would be even more type safe. The enums approach is not fully reflected in the PR and would need some additional design. Following a small example for the enum approach:

```proto
message EventExecution {
   optional AggregateTypeExecution aggregate_type = 1;
}

message AggregateTypeExecution {
   oneof type {
      UserAggregateExecution user_aggregate = 1;
      .
      .
      .
   }
}

message UserAggregateExecution {
   oneof type {
      bool user_human_added = 1;
      bool user_machine_added = 2;
      .
      .
      .
   }
}
```

```[tasklist]
### Tasks
- [ ] Review the proposed changes
- [ ] Discuss enum approach
- [ ] Change the proto message
- [ ] Change proto service
- [ ] Improve description in proto
- [ ] Change implementation on command side
- [ ] change implementation on query side
```

**Comment by adlerhurst** [comment]
Estimation:

0.25 review proposal
0.50 discuss enum proposal
0.25 proto changes
1.50 implementation command side
1.00 implementation query side

**Comment by stebenz** [comment]
Order of execution targets and includes is included in #7735 as the query side for the best match execution is the same topic
