### ISSUE TITLE
Implement zitadel.feature.v2gamma.FeatureService Commands

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#7755]
As a developer, I want to have an example service for a new mutlitenancy settings API command side with inheritance so I can test the experience by using it with all my API clients.

### Acceptance Criteria
- [ ] *zitadel.feature.v2gamma.FeatureService* PUT method is implemented
- [ ] *zitadel.feature.v2gamma.FeatureService* PATCH method is implemented
- [ ] *zitadel.feature.v2gamma.FeatureService* DELETE method is implemented
- [ ] The implementation adheres to #7592
- [ ] The FeatureService implements the behavior for [multitenancy enabled settings](https://github.com/zitadel/zitadel/blob/docs-resource-clusters/docs/docs/apis/v3.mdx). Especially resetting specific properties using PUT and PATCH is supported.
- [ ] The docs from #7649 are updated according to new learnings
- [ ] The API Guidelines from #7592 are updated according to new learnings
- [ ] Implementation in #7756 is updated according to new learnings 
- [ ] Subissues defined with #7649 are updated according to new learnings
- [ ] Standard logic is reused
- [ ] New standard logic is made reusable
- [ ] The implementation is unit tested
- [ ] The implementation is integration tested

**Comment by muhlemmer** [comment]
@eliobischof, @peintnermax. Earlier we discussed using the SetInstanceFeatureRequest for resetting individual features by means of a one-off between a set payload or a reset bool. However,  I was thinking currently the [ResetInstanceFeatures](https://zitadel.com/docs/apis/resources/feature_service_v2/feature-service-reset-instance-features) doesn't have a request body and resets all features for the instance.

We can also choose to add a request body there with a field for each feature that needs to be reset. I think that is a cleaner approach than a list of one-ofs. With the added benefit it is not a breaking change. This way the SetInstanceFeatureRequest can remain untouched and we do not have to refactor the frontend.

**Comment by eliobischof** [comment]
> @eliobischof, @peintnermax. Earlier we discussed using the SetInstanceFeatureRequest for resetting individual features by means of a one-off between a set payload or a reset bool. However,  I was thinking currently the [ResetInstanceFeatures](https://zitadel.com/docs/apis/resources/feature_service_v2/feature-service-reset-instance-features) doesn't have a request body and resets all features for the instance.
> 
> We can also choose to add a request body there with a field for each feature that needs to be reset. I think that is a cleaner approach than a list of one-ofs. With the added benefit it is not a breaking change. This way the SetInstanceFeatureRequest can remain untouched and we do not have to refactor the frontend.

We would like it very much to refactor the frontend 😃 as its implementation is very cumbersome atm.

The frontend is easy to implement if the GET response body can easily map to the PATCH or PUT request body.

Maybe something like
```
GET /features
{
  "someFeatureEnabled": {
    "value": true,
    "inherit": true,
    "source": "SYSTEM"
  }
}

PATCH /features
{
  "someFeatureEnabled": {
    "value": true,
    "inherit": false
  }
}

PATCH /features
{
  "someFeatureEnabled": {
    "value": true,  // ignored
    "inherit": true
  }
}
```

IMO we can ditch DELETE.

@peintnermax what do you think?

About breaking the API, we do that anyway soon for all resources. I would just start with the features service.

**Comment by eliobischof** [comment]
Closing as outdated
