### ISSUE TITLE
Implement zitadel.limit.v2alpha.LimitsService Commands

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#7756]
As a developer, I want to have an example service for a new mutlitenancy settings API command side so I can test the general experience by using it with all my API clients.

### Acceptance Criteria
- [ ] *zitadel.limit.v2alpha.LimitsService* PUT method is implemented
- [ ] *zitadel.limit.v2alpha.LimitsService* PATCH method is implemented
- [ ] *zitadel.limit.v2alpha.LimitsService* DELETE method is implemented
- [ ] The implementation adheres to #7592
- [ ] The implementation adheres to [multitenancy enabled settings](https://github.com/zitadel/zitadel/blob/docs-resource-clusters/docs/docs/apis/v3.mdx). Especially resetting specific properties using PUT and PATCH is supported.
- [ ] The docs from #7649 are updated according to new learnings
- [ ] The API Guidelines from #7592 are updated according to new learnings
- [ ] Subissues defined with #7649 are updated according to new learnings
- [ ] Standard logic for is reusable
- [ ] The implementation is unit tested
- [ ] The implementation is integration tested

### Optional
- [ ] Bulk limits

**Comment by eliobischof** [comment]
Not planned yet
