### ISSUE TITLE
Implement zitadel.feature.v2gamma.FeatureService Queries

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#7758]
As a developer, I want to have an example service for a new mutlitenancy settings API query side with inheritance so I can test the experience by using it with all my API clients.

### Acceptance Criteria
- [ ] *zitadel.feature.v2gamma.FeatureService* GET method is implemented
- [ ] The implementation adheres to #7592
- [ ] The FeatureService implements the behavior for [multitenancy enabled settings](https://github.com/zitadel/zitadel/blob/docs-resource-clusters/docs/docs/apis/v3.mdx). Especially inheritance information is returned with the property values.
- [ ] The docs from #7649 are updated according to new learnings
- [ ] The API Guidelines from #7592 are updated according to new learnings
- [ ] Implementation in #7756 is updated according to new learnings 
- [ ] Subissues defined with #7649 are updated according to new learnings
- [ ] Standard logic is reused
- [ ] New standard logic is made reusable
- [ ] The implementation is unit tested
- [ ] The implementation is integration tested

**Comment by eliobischof** [comment]
Closing as outdated
