### ISSUE TITLE
Command Side for Users with User Schemas (Updates)

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#7898]
As a ZITADEL Administrator I want to be able to update users and their states that apply to a predefined user schema, so I am able to ensure that my user data is consistent and applies to my standards.

## Acceptance Criteria
- [x] Feature is behind a feature flag
- [x] **UpdateUser**: changes an existing user. The type of a user cannot be changed
- [x] **LockUser**: changes the state of the user to `locked`
- [x] **UnlockUser**: changes the state of the user to `active` after it was locked
- [x] **ActivateUser**: changes the state of the user to `inactive`
- [x] **ReactivateUser**: changes the state of the user to `active` after it was locked
- [x]  the user data is filled according to the predefined user schema
- [x] As an admin I am able to change all fields that are defined as writeable by admin
- [x] As an end user I am not able to change fields that are only writeable by an admin
- [x] if user doesn't match the userschema, human readable error message is shown
- [x] I am able to change the user schema of a user, the schema is checked against the user information
   - [x] If only the schema changes, the current user information is checked for validity
   - [x] If the user schema changes and new user information is sent, the user schema is checked against the new user information
   - [x] User authenticators are checked against the new user schema
- [x] Detailed validation errors are returned to the user

## Todos

- [x] UpdateUser
- [x] LockUser
- [x] UnlockUser
- [x] DeactivateUser
- [x] ReactivateUser

### User Object
* **id**: unchangeble, unique identifier of the system
* **schema**: 
    * **type**: schema type of the user (e.g. human/machine)
    * **revision**: read only, revision of the schema the user was stored the last time (e.g. 4)
* **authenticators**: list of possibilites how a user can authenticate itself. there can be multiple authenticators of the same type
* **contact**: email and phone of the user if provided
* **state**: one of `Active`, `Inactive`, `Locked`, `Deleted`
* **data/profile/traits**: custom fields of a user based on the type (whats the best name for this?)

**Comment by hifabienne** [comment]
@eliobischof @stebenz as discussed I split the issue into create/delete and update functions.
Can you please estimate this?

https://github.com/zitadel/zitadel/issues/7308
