### ISSUE TITLE
Improve Benchmarking

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#8023]
With this issue, we consolidate our plans and communication about our efforts in benchmarking.

We want to achieve:

- [ ]  Identify which endpoints we want to benchmark and how they perform on ZITADEL Cloud so we know which bottlenecks we should optimize. Also consider https://github.com/zitadel/zitadel/issues/7639
- [ ] https://github.com/zitadel/DevOps/issues/29 Describe clear scaling advice so customers know their system requirements.
- [ ] #6585 Test the performance continuously with deterministic conditions to ensure ZITADEL keeps being performant
- [ ] #4424 Run stress tests to ensure ZITADEL scales as expected in real-world conditions and loads

**Comment by eliobischof** [comment]
@fforootd @adlerhurst Instead of closing the issues I found, they pretty much matched the points we identified and are already discussed. Therefore, I linked them and left them open. Are you fine with this? Did I miss something?

**Comment by fforootd** [comment]
Are the issue actionable already, to me most of it looks like "thoughts".

I think we should make clear what goals in what order we want to achieve.

**Comment by elinashoko** [comment]
Thanks for filing this issue. As part of an ongoing backlog cleanup, we're closing issues that have had no activity in over 12 months.

If this is still relevant, let us know in a comment (or reopen the issue) and we'll take another look.

This issue will close in 30 days if there's no further activity.
