### ISSUE TITLE
Lookup table

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#8094]
## Current state

Currently projections execute after event creation or scheduled. This leads to the requirement that during by ID queries we need to ensure the most recent state of projections, the current design of projections results in long running and blocking queries, additionally search results could be inconsistent. 

Searches of non aggregate ids are only possible after the data are projected because search the payload of events would be too expensive. This includes queries like client by client id or app by id as the ids are stored inside the payload of events.

## Proposal

Instead of projecting the data as a background job we introduce a new possibility to commands to define data which should be stored in a lookup table. This table allows fast search immediately after the commands are stored to the event store. It should be possible to add additional data to the aggregate later, for example by an asynchronous job which adds the login names to the fields of the aggregate.

## Design

Commands implement an interface method to write the fields to the lookup table described below. The table stores a field per row, which leads to multiple rows per object. If all data are present in the lookup table additional queries are not used anymore at all. The event store logic ensures consistency.

### `lookup`-table

The table is designed to store fields of an aggregate on a field per row fashion.

table design:

```sql
CREATE TABLE eventstore.fields (
    instance_id TEXT NOT NULL
    , resource_owner TEXT NOT NULL
    , aggregate_type TEXT NOT NULL
    , aggregate_id TEXT NOT NULL
    , field_name TEXT NOT NULL
    , number_value NUMERIC
    , text_value TEXT
    , CONSTRAINT one_of_values CHECK ((number_value IS NULL) <> (text_value IS NULL))
);
```

- The `field_name`-column should be a unique identifier of the field (e.g. `human.profile.first_name` for the users first name).
- Either `number_value` or `text_value` needs to be set

### Command side

The `eventstore.Command`-interface will be extended by the following method:

```go
type Command interface {
    ...
    LookupFields() []lookupFieldOption
}
```

The `lookupFieldOptions`-type allows to upsert or remove data from the `lookup`-table.

#### Example

```go
func (event *OIDCClientAddedEvent) LookupFields() []lookupFieldOption{
    return []lookupFieldOption{
        addLookupField(event.Aggregate(), "oidc.client_id", event.ClientID),
        ...
    }
}

func (event *RemoveInstanceEvent) LookupFields() []lookupFieldOption{
    return []lookupFieldOption{
        removeLookupFields(lookupFieldsByInstanceID(event.AggregateID())),
        ...
    }
}
```

### Query side

Instead of using the projected sql table to execute the search the query method should search in the `lookup`-table and if needed join the result to the existing table.

### Projection

Until a decision can be made if we continue with this new design projections remain as is and are extended.

New projections can be added to extend the rows of the `lookup`-table by computed fields.

## Questions

- ~~Would it be useful to add a value field per data type analog to `text_value`?~~ => https://github.com/zitadel/zitadel/issues/8094#issuecomment-2159951230
- ~~Which indexes should the table include?~~ => https://github.com/zitadel/zitadel/issues/8094#issuecomment-2159951230
- Decide which object to start with

```[tasklist]
## Tasks
- [x] Table design (0.5)
- [ ] Implement eventstore business logic (1)
- [ ] Implement command side of first object (1)
- [ ] Implement query side of first object (1)
- [ ] Add feature flag (0.5)
- [ ] Verify performance using load tests (0.5)
- [ ] Ensure no behaviour change (0.5)
```

**Comment by adlerhurst** [comment]
Is part of https://github.com/zitadel/zitadel/issues/8094

**Comment by adlerhurst** [comment]
> Would it be useful to add a value field per data type analog to text_value?

First analysis shows that adding a field per datatype improves query speed:

```psql
         Table "projections.test_jsonb"
 Column | Type  | Collation | Nullable | Default 
--------+-------+-----------+----------+---------
 key    | text  |           |          | 
 value  | jsonb |           |          | 
Indexes:
    "value_idx" btree (value)
    "value_idx_n" btree ((value::numeric))

WITH numbers AS (
  SELECT 
    generate_series(1,1000000) AS id, 
    random() * 10 AS n
)
insert into test_dt (key, "number") select cast(id as text), n from numbers;

explain analyze select count(*) from test_jsonb where cast("value" as numeric) < 0.05;;
                                                                QUERY PLAN                                                                
------------------------------------------------------------------------------------------------------------------------------------------
 Finalize Aggregate  (cost=15629.33..15629.34 rows=1 width=8) (actual time=133.325..136.943 rows=1 loops=1)
   ->  Gather  (cost=15629.12..15629.33 rows=2 width=8) (actual time=133.179..136.934 rows=3 loops=1)
         Workers Planned: 2
         Workers Launched: 2
         ->  Partial Aggregate  (cost=14629.12..14629.13 rows=1 width=8) (actual time=64.682..64.683 rows=1 loops=3)
               ->  Parallel Seq Scan on test_jsonb  (cost=0.00..14264.53 rows=145834 width=0) (actual time=64.678..64.679 rows=0 loops=3)
                     Filter: ((value)::numeric < 0.05)
                     Rows Removed by Filter: 350002
 Planning Time: 1.042 ms
 Execution Time: 137.358 ms
(10 rows)
```
