### ISSUE TITLE
[Epic]: OIDC Back-Channel Logout

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#8287]
Currently ZITADEL supports RP-initiated logout for clients. Back-channel logout ensures that user sessions are terminated across all connected applications, even if the user closes their browser or loses connectivity providing a more secure alternative for certain use cases.

### Describe your ideal solution

ZITADEL supports OpenID Connect [Back-Channel Logout](https://openid.net/specs/openid-connect-backchannel-1_0.html).

## Acceptance criteria

- [x] https://github.com/zitadel/oidc/issues/642
- [x] https://github.com/zitadel/zitadel/issues/8467
- [x] https://github.com/zitadel/zitadel/issues/8468
- [ ] https://github.com/zitadel/zitadel/issues/8469

**Comment by muhlemmer** [comment]
@mffap I changed you description. We currently only support [RP-Initiated logout](https://openid.net/specs/openid-connect-rpinitiated-1_0.html). Not front-channel or back-channel.

If front channel is also required, we should create another issue.

**Comment by muhlemmer** [comment]
Post investigation notes:

In the OIDC lib we need to add (**1 day**):

- `op.Client` interface to return a back-channel logout URI
- Discovery response to include the `backchannel_logout_supported` and `backchannel_logout_session_supported` fields
- Logout Token type definition and constructors

As the OP implementation needs to initiate the logout and push the request to the RPs, there is no new endpoint or other implementation to be done in OIDC.

Inside zitadel we need to do a little more.

- Add a feature flag. When enabled, discovery endpoint will advertise `backchannel_logout_supported` and `backchannel_logout_session_supported` fields. (**0.5 days**)
- Add back-channel logout URI the OIDC app / client configs (**2 days**):
   - Update proto definitions
   - Writemodel
   - Projections
   - Console UI
 - Add the ability to search all the user's sessions and associated clients in the command side (**2 days**).
   - Define searchable fields for session events in the search table
   - Define searchable fields for client IDs with back-channel logout URI payload
   - Setup job for search table
- Add a notification channel for back channel logout or SET in general (**?? days**)
  - Back-channel logout refers to [RFC 8935
Push-Based Security Event Token (SET) Delivery Using HTTP
](https://www.rfc-editor.org/rfc/rfc8935.html) for sending the logout token
  - Back-channel logout requires retries in certain cases
- The initiator of back-channel logout is currently not defined by this user story or standard. Extra time must be added to estimation once we do define it, or a separate user story.

<hr>

### Functional

 Proposed functional flow:

1. Something triggers back-channel logout (what?).
2. Command side searches for all sessions and creates a termination event for each.
3. Command side searches for all clients with a  back-channel logout URI with the clientIDs from above sessions.
4. For each found back-channel logout URI a notify event is created for the `SET` channel
5. All events are pushed
6. The notification framework takes care of parallel / async delivery, with possible retries as defined in the standard and RFC.

  <hr>
  
### Caveats

This estimation depends on the availability and stability of the search table, introduced in https://github.com/zitadel/zitadel/pull/8191. It is currently still under evaluation and its internal API may change, potentially increasing or decreasing complexity of its use.

**Comment by muhlemmer** [comment]
SET notification channel could be implemented / combined with https://github.com/zitadel/zitadel/issues/8270

**Comment by livio-a** [comment]
> SET notification channel could be implemented / combined with [#8270](https://github.com/zitadel/zitadel/issues/8270)

i'll check that with @adlerhurst

**Comment by muhlemmer** [comment]
Another note. Back-Channel can be initiated by [RP-initiated logout](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout). If that is the case, we need to keep the following in mind:

> As part of the OP logging out the End-User, the OP uses the logout mechanism(s) registered by the RPs to notify any RPs logged in as that End-User that they are to likewise log out the End-User. RPs can use any of [OpenID Connect Session Management 1.0](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#OpenID.Session) [OpenID.Session], [OpenID Connect Front-Channel Logout 1.0](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#OpenID.FrontChannel) [OpenID.FrontChannel], and/or [OpenID Connect Back-Channel Logout 1.0](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#OpenID.BackChannel) [OpenID.BackChannel] to receive logout notifications from the OP, depending upon which of these mechanisms the OP and RPs mutually support. The RP initiating the logout is to be included in these notifications before the post-logout redirection defined in [Section 3](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RedirectionAfterLogout) is performed.

This means the Login UI (v1 and v2) needs to serve a page on the End Session endpoint asking the user about OP logout.

**Comment by muhlemmer** [comment]
@livio-a as discussed, this issue is now an epic and sub-issues are created with the estimations. If you have some time, can you please review the plan?

The only thing that is not clear for me, is how do we want to do end session on the typescript repo. At the moment I assumed we need an EndSession method on the OIDCService. But perhaps there is a better solution, like a simple query param we check for on the current end session handler.

**Comment by ben-foxmoore** [comment]
I think this page was never updated now that Back-Channel Logout is supported: https://zitadel.com/docs/guides/integrate/login/oidc/logout#back-channel-logout

**Comment by adlerhurst** [comment]
Thanks @ben-foxmoore the docs are up-to-date now.
