### ISSUE TITLE
Console add user based on schemas

### ISSUE THREAD

**Issue by stebenz** [zitadel/zitadel#8315]
As a ZITADEL administrator I want to be able to manage my users depending on the defined user schemas in the console.

## Todos

- [ ] Create user with defined user schema
- [ ] Update user with defined user schema, status changes also possible #7898
- [ ] Remove user with defined user schema
- [ ] Update schema from existing user #8313 

## Additional information

Command side create and delete for users #7308 
Command side updates for users #7898

**Comment by elinashoko** [comment]
Thanks for filing this issue. As part of an ongoing backlog cleanup, we're closing older `area/console` issues.

We're building a replacement for the Console with significantly better usability, and that's where our focus is right now. As a result, the current Console is planned for deprecation over the next 12 months, and we're not prioritizing fixes or improvements to it in the meantime.

If this is still an active problem for you, let us know in a comment (or reopen the issue) and we'll take another look.

This issue will close in 30 days if there's no further activity.

**Comment by elinashoko** [comment]
Thanks for filing this issue. As part of an ongoing backlog cleanup, we're closing issues that have had no activity in over 12 months.

If this is still relevant, let us know in a comment (or reopen the issue) and we'll take another look.

This issue will close in 30 days if there's no further activity.
