### ISSUE TITLE
Mapping for OIDC claims and SAML attributes can be defined for fields of the schema

### ISSUE THREAD

**Issue by stebenz** [zitadel/zitadel#8317]
As a ZITADEL administrator I want to be able to define oidcClaim definitions on the user schema, which then can be used to map attributes to fill into oidc claims.

## Todos

- [ ] Verification for given claims/attributes in user schema to be used
- [ ] Add/remove claim/attribute definitions from user schema

## Additional information

userschema definition with oidcClaima and saml attribute as attribute https://github.com/zitadel/zitadel/issues/6433#issuecomment-1867508702

**Comment by hifabienne** [comment]
@stebenz @eliobischof can you please estimate this?

**Comment by oliwel** [comment]
I want to add a point to this list which is crucial for GDPR compliance: 
- [ ] As an administrator I want to define what claims can be requested by a project

Business Case: I want to make the "Human Resources Employee ID" available to applications of the HR department while preventing other applications to see this information.

**Comment by elinashoko** [comment]
Thanks for filing this issue. As part of an ongoing backlog cleanup, we're closing issues that have had no activity in over 12 months.

If this is still relevant, let us know in a comment (or reopen the issue) and we'll take another look.

This issue will close in 30 days if there's no further activity.
