### ISSUE TITLE
IDPs user data is mapped base on schema (all different types)

### ISSUE THREAD

**Issue by stebenz** [zitadel/zitadel#8320]
As a ZITADEL administrator I want to be able to have the defined mappings in the user schema to fill in the user information on login with an external IDP.

## Todos

- [ ] Function to handle OIDC claims into user information
- [ ] Function to handle OAuth into user information
- [ ] Function to handle SAML attributes into user information
- [ ] Function to handle LDAP into user information

**Comment by hifabienne** [comment]
@eliobischof @stebenz can you please estimate this issue?

**Comment by elinashoko** [comment]
Thanks for filing this issue. As part of an ongoing backlog cleanup, we're closing issues that have had no activity in over 12 months.

If this is still relevant, let us know in a comment (or reopen the issue) and we'll take another look.

This issue will close in 30 days if there's no further activity.
