### ISSUE TITLE
[Epic] Improve logging Structure (also for multi instance scenarios)

### ISSUE THREAD

**Issue by livio-a** [zitadel/zitadel#8408]
As a System Administrator/Operator,
I want all system logs to follow a common, structured format that includes essential contextual information (like instanceID),
So that I can easily filter, search, and aggregate logs across single or multiple instances, enabling efficient troubleshooting, monitoring, and paving the way for instance-specific log access and customer analytics.

## Description

Currently, log entries across the system lack a unified structure, particularly concerning contextual information. This inconsistency makes it challenging to effectively filter and analyze logs, especially in multi-instance deployments like zitadel.cloud. For example, pinpointing logs for a specific customer instance or tracing a request across services is difficult and time-consuming.

To address this, we need to define and implement a common logging format. This format must include key contextual details, with instanceID being a primary requirement. Other fields to consider (though the final list is TBD) could include traceID, spanID, userID, serviceName, requestID, and hostname/podName.

This foundational improvement will significantly enhance our operational capabilities. It's a critical enabler for future features such as providing ZITADEL Cloud administrators access to logs pertinent to their specific instances and empowering customers with the ability to perform analytics on their usage data. The new structure should be designed with extensibility in mind to accommodate future contextual information needs.

## Acceptance Criteria
- [ ] Standardized Log Entry Format & Key Identifiers
  - Given: The new standardized logging structure is implemented across all relevant services.
  - When: Any service component generates a log entry.
  - Then:
    - [ ] The log entry MUST contain a dedicated, accurately populated field for instanceID.
    - [x] The log entry MUST adhere to the defined common structured format (e.g., JSON, logfmt).
    - [x] The log entry MUST include fundamental fields like timestamp, severity level, and the name of the emitting service/component.
- [x] Inclusion of Traceability Information
  - Given: The new standardized logging structure is implemented, and distributed tracing is active for a request.
  - When: A log entry is generated for an operation that is part of that distributed trace.
  - Then:
    - The log entry SHOULD include a traceID consistent with the overall trace.
    - The log entry SHOULD include a spanID if applicable to the specific operation within the trace.
- [ ] Instance-Specific Log Filtering
  - Given: Logs from multiple instances, formatted with the new standard, are being collected in a centralized logging system (e.g., Elasticsearch, Grafana Loki).
  - When: An administrator or an automated tool queries the logging system to filter logs by a specific instanceID.
  - Then:
    - Only log entries originating from the specified instanceID are returned.
    - The filtering mechanism effectively isolates instance-specific logs.
- [ ] Advanced Log Querying with Multiple Contextual Fields
  - Given: Structured logs are available in the central logging system.
  - When: An administrator executes a query combining instanceID with other defined contextual fields (e.g., userID, serviceName, traceID, requestID).
  - Then:
    - The system accurately returns only the log entries that match all specified query parameters.
Complex troubleshooting and analysis based on multiple contexts are possible.
- [x] Log Message Clarity and Utility
  - Given: A log entry is generated according to the new standard.
  - When: A developer or operator views a raw or processed log entry.
  - Then:
    - The entry's structure is consistent, making it easily machine-parsable by logging tools.
    - The entry is human-readable, allowing for quick understanding of the event's context without ambiguity.
- [x] Extensibility of the Logging Context
  - Given: The common logging framework supporting the new structured format is in place.
  - When: A future development requires adding a new, globally relevant contextual field to the logs.
  - Then:
    - The logging framework allows for the addition of this new contextual field without requiring code modifications in every single logging statement across all services.
    - Existing log parsers and dashboards can be adapted or continue to function with the augmented log structure.
- [x] Performance Impact of Structured Logging
  - Given: The system is operating with the new structured logging implemented.
  - When: The system is processing requests and generating logs under typical and peak load conditions.
  - Then:
    - The performance overhead (e.g., CPU utilization, memory footprint, I/O operations, log ingestion latency) directly attributable to the new structured logging mechanism is within predefined acceptable limits.
    - Application response times are not measurably degraded due to the enhanced logging.
- [ ] Documentation of the Logging Standard
  - Given: The new logging structure and framework are finalized and implemented.
  - When: A developer, operator, or administrator needs to understand or utilize the logging system.
  - Then:
    - Comprehensive documentation is readily available and clearly defines:
    - The common log format and its schema.
    - All mandatory and commonly used optional contextual fields, their data types, expected values, and their semantic meaning.
    - Best practices and guidelines for developers on generating meaningful and structured logs within applications.
    - Instructions on how to query and filter the structured logs effectively in the central logging system.
    - Procedures for extending the logging context with new fields, if applicable.

**Comment by livio-a** [comment]
also relates to https://github.com/zitadel/zitadel/pull/8376#issue-2442146876

**Comment by fforootd** [comment]
Yes, I have not yet concluded the structure, will try to work on this in the next few days

**Comment by fforootd** [comment]
I gave it some thought and this is what I came up with. I tried to keep it as "lean" as possible. Hence I opted for properties on the root instead of cascaded objects. 

Explanation of some words I chose:

Streams -> a stream of data from a certain component
Metadata -> can carry additional fields used to describe additional context supplied by the streams

```js
{
  timestamp: ISO_8601_Timestamp, 
  stream: 'events' | 'http' | 'runtime' | 'access' | 'action' | 'more?',
  severity: 'debug' | 'info' | 'warn' | 'error' | 'fatal', // Needs to be verified
  instance_id: String, // The instance_id or null if it not resolved
  message: String,  // (Optional)
  stack_trace: String,    // (Optional)
  http_request: {
    host: String, // The domain that has been used to call the instance
    method: 'GET' | 'POST' | 'PUT' | 'DELETE' | ... , 
    path: String, // The path or method (grpc) used to call the http server
    status: Number,
    grpc_status: Number, // Optional
    user_agent: String,
    referer: String,
    remote_ip: String,
    request_headers: { ... }, // (Optional, be mindful of sensitive data)
    response_headers: { ... }, // (Optional, be mindful of sensitive data)
    request_body: String, // (Optional, be mindful of sensitive data)
    response_body: String, // (Optional, be mindful of sensitive data)
    duration: Number // (Optional, in milliseconds)
  }, // Only on stream type http
  action_request: 
  {
    // Todo
  },
  metadata: { 
    event_type: 'user_created' | 'user_updated' | ... , // (Optional, for event_sourcing)
    module: 'openid' | 'saml' | ... , // (Optional, for runtime logs)

    // ... other component-specific fields as needed
  }
}
```

@livio-a what do you think of this?

**Comment by eliobischof** [comment]
This is partially implemented with #8613 
It allows to send activity logs in batches to cloud logging.
It only sends activity logs for the moment, as these are well structured and suitable for many analytics cases.

**Comment by eliobischof** [comment]
@fforootd and @livio-a I'd like to work on this in the new engineering sprint as it enables implementing more sophisticated queries for customers and employees for debugging, auditing and analytics purposes.

I'm going to 
- [ ] work out a more concrete proposal for how we should structure the logs considering your proposal above and
- [ ] enforce this structure technically at the time of logging in the code.

These two items are independent tasks.

I'll come back to you once I have an opinion about the structure so we can decide quickly if you don't mind.

Do you already have opinions about this?

**Comment by fforootd** [comment]
Consider this an additional input. Maybe we should just use the [otel log format](https://opentelemetry.io/docs/specs/otel/logs/data-model) since it is stable.

It already has most of the fields we would need and we could use the `resource` field to track what component emitted something.

There are also mapping guidelines here for different sinks including [google cloud ](https://opentelemetry.io/docs/specs/otel/logs/data-model-appendix/#google-cloud-logging)

**Comment by fforootd** [comment]
From slack

Lets define the messages for these streams and define what the common fields are that they share.

- requests (http/grpc)
- actions (logs from actions)
- events (the events :D)
- runtime (panics, startup, healthcheck, db connections, configs error, migrations)
- notifications (email, sms, webhooks)

**Comment by eliobischof** [comment]
> From slack
> 
> Lets define the messages for these streams and define what the common fields are that they share.
> 
> * requests (http/grpc)
> * actions (logs from actions)
> * events (the events :D)
> * runtime (panics, startup, healthcheck, db connections, configs error, migrations)
> * notifications (email, sms, webhooks)

I made a new proposal:
https://docs-git-docs-streams-zitadel.vercel.app/docs/self-hosting/stream/reference
