### ISSUE TITLE
ZITADEL V3

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#8599]
This release fully integrates the new Zitadel Actions, alongside revamped task handling for improved reliability, cleaned-up APIs by removing beta versions, and streamlined database support to PostgreSQL for enhanced performance and maintainability. 

## Acceptance Criteria
- [x] Cockroach Support is fully removed and documentation is up to date
- [x] Introduction of new async taks management https://github.com/zitadel/zitadel/issues/9277
- [x] Clean Up APIs
   - [x] Move Alpha V3 to v2 to make it easier to understand
- [x] Actions V2
- [x] Release Cycle Change: From V3 Release ongoing we will switch to a quarterly release cycle https://github.com/zitadel/zitadel/discussions/9417

**Comment by JakobStadlhuber** [comment]
@hifabienne amazing except for the licence change from Apache to AGPLv3, this would be a a huge disappointment. Is this already 100% decided?

**Comment by adlerhurst** [comment]
A task to update [the charts repo](https://github.com/zitadel/zitadel-charts) is missing, currently it defaults to cockroach.

**Comment by hifabienne** [comment]
> A task to update [the charts repo](https://github.com/zitadel/zitadel-charts) is missing, currently it defaults to cockroach.

Can you add a sub issue for this directly, and add it to the current sprint? As far as I understand this is something we need to implement to release v3? In that case we will need to check who can take that over
