### ISSUE TITLE
[Epic]: Object cache

### ISSUE THREAD

**Issue by muhlemmer** [zitadel/zitadel#8648]
We would like to increase the performance of zitadel. One of the methods to achieve this, is by caching frequently used objects.
In order to satisfy different operational needs we want to support multiple storage back-ends.
A cache should be able to resolve a single object using multiple keys.

## Acceptance criteria

- [ ] Interface which abstracts the different storage solutions: https://github.com/zitadel/zitadel/pull/8628

### Storage

- [ ] No-op, disabled cache: https://github.com/zitadel/zitadel/pull/8628
- [ ] Application memory: https://github.com/zitadel/zitadel/pull/8628
- [ ] https://github.com/zitadel/zitadel/issues/8647
- [ ] https://github.com/zitadel/zitadel/issues/8130

### Objects

- [ ] Instance by domain and ID: https://github.com/zitadel/zitadel/pull/8628
- [ ] Organization by ID
- [ ] User By ID,  username, (email?)
- [ ] Userinfo response

**Comment by elinashoko** [comment]
Thanks for filing this issue. As part of an ongoing backlog cleanup, we're closing issues that have had no activity in over 12 months.

If this is still relevant, let us know in a comment (or reopen the issue) and we'll take another look.

This issue will close in 30 days if there's no further activity.
