### ISSUE TITLE
Milestone events

### ISSUE THREAD

**Issue by muhlemmer** [zitadel/zitadel#8800]
Currently milestones use existing events from a number of aggregates. OIDC session is one of them. We noticed in load-tests that the reduction of the oidc_session.added event into the milestone projection is a costly business with payload based conditionals. A milestone is reached once, but even then we remain subscribed to the OIDC events. This requires the `projections.current_states` to be updated continuously.

The milestone creation should be refactored to use dedicated events instead. The command side knows the business logic and should decide to push a milestone reached event only once.

## Acceptance criteria

- [x] Add a milestone reached event
- [x] Command side uses a write model to determine if a milestone was already reached.
- [x] Command side creates a milestone reached event when:
  - [x] The milestone wasn't already reached
  - [x] InstanceCreated: always for a new instance
  - [x] AuthenticationSucceededOnInstance: any new OIDC session
  - [x] ProjectCreated: when a project is created by a non-system user. (The first project is created by the system user that creates the instance)
  - [x] ApplicationCreated: when an OIDC or SAML app config is created by a non-system user. (Console app is created by the system user that creates the instance)
  - [x] AuthenticationSucceededOnApplication: a new OIDC session for an application which is not the Console
  - [x] InstanceRemoved: always when an instance is deleted.
- [x] Caching is used for the instance's milestone state
