### ISSUE TITLE
replace `distinct instance_id` query by cache

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#8999]
During load tests we saw expensive database queries to compute the recently active instances. These queries must be replaced.

```[tasklist]
### Tasks
- [ ] Ensure that all instance domains are stored on command side. (Using fields table) #9000
- [ ] Query the instance by host query to use the fields table #9000
- [ ] Cache the lately active instances
  - [ ] Add a middleware on grpc and http to store the instance ids
- [ ] Use these instance ids in spooler logic instead of querying the eventstore
```
