### ISSUE TITLE
[Epic] Collect Feedback about Beta-Features

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#9006]
As an engineer and product manager of ZITADEL we want to get feedback from our customers about new beta-features we have released, to be able to improve them and move to GA.

Customers can enable beta features on their own through feature flags for the instance. Once they have enabled a feature we want to know if they are satisfied or if they experience any problems.

## Acceptance Criteria
- [ ] When a beta feature is enabled in console, customer have the possiblity to fill out a survey about the feature
- [ ] Following questions should be presented:
    - [ ] How satisfied are you with the beta feature? (Please rate on a scale of 1-10, where 1 is very dissatisfied and 10 is very satisfied.)
    - [ ] Did you encounter any bugs or errors while using the beta feature? If so, please describe them.
    - [ ] Please share any additional comments or suggestions about the beta feature.
- [ ] Users can easily submit their feedback.

## Additional Information
Can we use post hog surveys for this?

**Comment by elinashoko** [comment]
Thanks for filing this issue. As part of an ongoing backlog cleanup, we're closing issues that have had no activity in over 12 months.

If this is still relevant, let us know in a comment (or reopen the issue) and we'll take another look.

This issue will close in 30 days if there's no further activity.
